/* Diccionario de acrónimos de ciberseguridad: más de 190 términos
   con definiciones en español, organizados por dominio. */

export type AcroCat = 'ofensivo' | 'defensivo' | 'redes' | 'cripto' | 'win-ad' | 'linux' | 'web' | 'cloud' | 'gobierno' | 'forense'

export interface Acronym { a: string; d: string; cat: AcroCat }

export const ACRO_CATS: { id: AcroCat; label: string; icon: string }[] = [
  { id: 'ofensivo', label: 'Ofensivo', icon: '⚔️' },
  { id: 'defensivo', label: 'Defensivo', icon: '🛡️' },
  { id: 'redes', label: 'Redes', icon: '🌐' },
  { id: 'cripto', label: 'Cripto', icon: '🔐' },
  { id: 'win-ad', label: 'Windows/AD', icon: '🪟' },
  { id: 'linux', label: 'Linux', icon: '🐧' },
  { id: 'web', label: 'Web', icon: '🕸️' },
  { id: 'cloud', label: 'Cloud', icon: '☁️' },
  { id: 'gobierno', label: 'Gobierno y marco', icon: '📋' },
  { id: 'forense', label: 'Forense y Malware', icon: '🔬' },
]

export const ACRONYMS: Acronym[] = [
  // ofensivo
  { a: 'APT', d: 'Advanced Persistent Threat — grupo de atacantes con recursos y persistencia prolongada, normalmente patrocinado por un Estado', cat: 'ofensivo' },
  { a: 'AV', d: 'Antivirus / Anti-Virus — software de detección de malware por firmas y heurística', cat: 'ofensivo' },
  { a: 'BOF', d: 'Buffer Overflow — desbordamiento de buffer para sobrescribir memoria y ejecutar código', cat: 'ofensivo' },
  { a: 'C2 / C&C', d: 'Command and Control — infraestructura desde la que un atacante dirige sus implants', cat: 'ofensivo' },
  { a: 'CVE', d: 'Common Vulnerabilities and Exposures — identificador único de vulnerabilidad (CVE-2024-1234)', cat: 'ofensivo' },
  { a: 'CVSS', d: 'Common Vulnerability Scoring System — puntuación 0-10 de severidad de una CVE', cat: 'ofensivo' },
  { a: 'DoS / DDoS', d: '(Distributed) Denial of Service — saturar un servicio hasta tirarlo; DDoS desde muchos orígenes', cat: 'ofensivo' },
  { a: 'EOP', d: 'Execution Of Payload / Escape from Path... en pentest se usa como "ejecutar código con éxito"', cat: 'ofensivo' },
  { a: 'exploit', d: 'código o técnica que aprovecha una vulnerabilidad para provocar un comportamiento no previsto', cat: 'ofensivo' },
  { a: 'fuzzing', d: 'envío automatizado de datos malformados para descubrir fallos de parsing', cat: 'ofensivo' },
  { a: 'GTFOBins', d: 'base de datos de binarios UNIX abusables para privesc (sudo, SUID, capabilities)', cat: 'ofensivo' },
  { a: 'LOLBAS', d: 'Living Off The Land Binaries And Scripts — binarios legítimos de Windows abusables (certutil, bitsadmin…)', cat: 'ofensivo' },
  { a: 'LFI', d: 'Local File Inclusion — inclusión de ficheros locales vía parámetro sin sanear', cat: 'ofensivo' },
  { a: 'RFI', d: 'Remote File Inclusion — igual pero con URL remota (requiere allow_url_include)', cat: 'ofensivo' },
  { a: 'OSINT', d: 'Open Source Intelligence — inteligencia a partir de fuentes públicas', cat: 'ofensivo' },
  { a: 'payload', d: 'carga útil del exploit: el código que se ejecuta tras aprovechar la vulnerabilidad', cat: 'ofensivo' },
  { a: 'privesc', d: 'privilege escalation — escalar de usuario normal a root/SYSTEM', cat: 'ofensivo' },
  { a: 'RCE', d: 'Remote Code Execution — ejecución de código arbitrario en remoto: la vuln más grave', cat: 'ofensivo' },
  { a: 'red team', d: 'equipo que simula atacantes reales con técnicas de adversario, con autorización', cat: 'ofensivo' },
  { a: 'ROP', d: 'Return-Oriented Programming — encadenar gadgets de código existente para evadir DEP', cat: 'ofensivo' },
  { a: 'shellcode', d: 'código máquina inyectado por un exploit (típicamente una reverse shell)', cat: 'ofensivo' },
  { a: 'SQLi', d: 'SQL Injection — inyección de SQL vía entradas sin sanear', cat: 'ofensivo' },
  { a: 'XSS', d: 'Cross-Site Scripting — ejecución de JS en el navegador de la víctima vía entrada no saneada', cat: 'ofensivo' },
  { a: 'SSRF', d: 'Server-Side Request Forgery — hacer que el servidor haga peticiones a URLs elegidas por el atacante', cat: 'ofensivo' },
  { a: 'XXE', d: 'XML eXternal Entity — inyección de entidades XML externas para leer ficheros o SSRF', cat: 'ofensivo' },
  { a: 'zero-day / 0day', d: 'vulnerabilidad sin parche ni conocimiento público', cat: 'ofensivo' },
  { a: 'CTF', d: 'Capture The Flag — competición de retos de seguridad (Jeopardy, Attack-Defense)', cat: 'ofensivo' },
  { a: 'OPSEC', d: 'Operational Security — minimizar la huella que dejas como atacante (o como defensor)', cat: 'ofensivo' },

  // defensivo
  { a: 'SOC', d: 'Security Operations Center — equipo que monitoriza y responde a incidentes 24/7', cat: 'defensivo' },
  { a: 'CSIRT', d: 'Computer Security Incident Response Team — equipo de respuesta a incidentes (a veces sin SOC 24/7)', cat: 'defensivo' },
  { a: 'CTI', d: 'Cyber Threat Intelligence — inteligencia de amenazas: TTPs, IOCs y actores relevantes para tu sector', cat: 'defensivo' },
  { a: 'SIEM', d: 'Security Information and Event Management — agregación y correlación de logs (Splunk, Elastic, Wazuh)', cat: 'defensivo' },
  { a: 'SOAR', d: 'Security Orchestration, Automation and Response — automatización de respuestas del SOC', cat: 'defensivo' },
  { a: 'IDS / IPS', d: 'Intrusion Detection/Prevention System — detecta (IDS) o bloquea (IPS) tráfico malicioso (Snort, Suricata)', cat: 'defensivo' },
  { a: 'EDR', d: 'Endpoint Detection and Response — antivirus de nueva generación con telemetría y respuesta remota', cat: 'defensivo' },
  { a: 'XDR', d: 'Extended Detection and Response — EDR que fusiona endpoints, red, identidad y cloud', cat: 'defensivo' },
  { a: 'MDR', d: 'Managed Detection and Response — EDR/SIEM gestionado por un tercero', cat: 'defensivo' },
  { a: 'NGFW', d: 'Next-Generation Firewall — firewall con inspección de aplicación, IPS e intel de amenazas', cat: 'defensivo' },
  { a: 'WAF', d: 'Web Application Firewall — filtra peticiones HTTP maliciosas hacia una web', cat: 'defensivo' },
  { a: 'NDR', d: 'Network Detection and Response — detección de amenazas a nivel de tráfico (Zeek, Corelight)', cat: 'defensivo' },
  { a: 'DLP', d: 'Data Loss Prevention — prevención de fuga de datos sensibles (email, USB, cloud)', cat: 'defensivo' },
  { a: 'MFA / 2FA', d: 'Multi-Factor Authentication — algo que sabes + algo que tienes/eres', cat: 'defensivo' },
  { a: 'SSO', d: 'Single Sign-On — una autenticación para todos los servicios (SAML, OIDC)', cat: 'defensivo' },
  { a: 'PAM', d: 'Privileged Access Management — gestión y grabación de sesiones de cuentas privilegiadas', cat: 'defensivo' },
  { a: 'IAM', d: 'Identity and Access Management — ciclo de vida completo de identidades y permisos', cat: 'defensivo' },
  { a: 'TTP', d: 'Tactics, Techniques and Procedures — cómo opera un adversario (base de MITRE ATT&CK)', cat: 'defensivo' },
  { a: 'IOC', d: 'Indicator of Compromise — evidencia observable de una intrusión (IP, hash, dominio)', cat: 'defensivo' },
  { a: 'IOA', d: 'Indicator of Attack — comportamiento sospechoso previo al compromiso (vs IOC que es posterior)', cat: 'defensivo' },
  { a: 'UEBA', d: 'User and Entity Behavior Analytics — detección de anomalías por comportamiento', cat: 'defensivo' },
  { a: 'honeypot', d: 'sistema señuelo para atraer y estudiar atacantes', cat: 'defensivo' },
  { a: 'threat hunting', d: 'búsqueda proactiva de amenazas que las alertas no han detectado', cat: 'defensivo' },
  { a: 'false positive', d: 'alerta que se dispara sin que haya amenaza real', cat: 'defensivo' },
  { a: 'hardening', d: 'endurecimiento: reducir superficie de ataque aplicando configuraciones seguras', cat: 'defensivo' },
  { a: 'patch management', d: 'ciclo de inventariado, priorización y aplicación de parches', cat: 'defensivo' },
  { a: 'vulnerability scan', d: 'escaneo automatizado de vulnerabilidades conocidas (Nessus, OpenVAS)', cat: 'defensivo' },
  { a: 'purple team', d: 'colaboración red+blue: validar que las detecciones funcionan contra técnicas reales', cat: 'defensivo' },

  // redes
  { a: 'ACL', d: 'Access Control List — reglas de filtrado en routers/firewalls (wildcards en Cisco)', cat: 'redes' },
  { a: 'ARP', d: 'Address Resolution Protocol — mapea IP→MAC en LAN; el spoofing de ARP es el envenenamiento clásico', cat: 'redes' },
  { a: 'AS', d: 'Autonomous System — conjunto de redes bajo una misma política de enrutamiento BGP', cat: 'redes' },
  { a: 'BGP', d: 'Border Gateway Protocol — el enrutamiento entre ASes de internet (hijack de BGP = secuestro de rutas)', cat: 'redes' },
  { a: 'BSSID / SSID', d: 'MAC del punto de acceso / nombre de la red WiFi', cat: 'redes' },
  { a: 'CIDR', d: 'Classless Inter-Domain Routing — notación IP/prefijo (10.0.0.0/8)', cat: 'redes' },
  { a: 'DHCP', d: 'Dynamic Host Configuration Protocol — asignación automática de IPs (spoofing de DHCP = MITM)', cat: 'redes' },
  { a: 'DNS', d: 'Domain Name System — resolución de nombres; su abuso: túneles DNS, DNS hijacking, DGA', cat: 'redes' },
  { a: 'DoH / DoT', d: 'DNS over HTTPS / TLS — DNS cifrado para evitar sniffing (y censura corporativa)', cat: 'redes' },
  { a: 'DMZ', d: 'DeMilitarized Zone — segmento de red que expone servicios públicos aislados de la LAN', cat: 'redes' },
  { a: 'DSCP', d: 'Differentiated Services Code Point — marca QoS en el byte ToS (EF=46 para voz)', cat: 'redes' },
  { a: 'ICMP', d: 'Internet Control Message Protocol — mensajes de control (ping, dest unreachable); también exfil y tunneling', cat: 'redes' },
  { a: 'IPsec', d: 'conjunto de protocolos de cifrado a nivel IP (IKE, ESP, AH): VPNs site-to-site', cat: 'redes' },
  { a: 'LACP', d: 'Link Aggregation Control Protocol — agrupa enlaces físicos en uno lógico (port-channel)', cat: 'redes' },
  { a: 'LLMNR / NBT-NS', d: 'protocolos de resolución local de Windows; su poisoning (Responder) es el ataque interno #1', cat: 'redes' },
  { a: 'MAC', d: 'Media Access Control — dirección física de la interfaz (y Control de Acceso al Medio como función)', cat: 'redes' },
  { a: 'MSS', d: 'Maximum Segment Size — tamaño máximo de payload TCP (MSS = MTU − 40 en IPv4)', cat: 'redes' },
  { a: 'MTU', d: 'Maximum Transmission Unit — tamaño máximo de paquete por enlace (1500 en Ethernet)', cat: 'redes' },
  { a: 'NAT', d: 'Network Address Translation — traducción de IPs privadas a públicas', cat: 'redes' },
  { a: 'NTP', d: 'Network Time Protocol — sincronización de relojes (crítica para Kerberos y logs)', cat: 'redes' },
  { a: 'OSPF', d: 'Open Shortest Path First — protocolo de enrutamiento interior (IGP) por estado de enlace', cat: 'redes' },
  { a: 'PoE', d: 'Power over Ethernet — alimentación eléctrica por el cable de red (APs, cámaras, teléfonos)', cat: 'redes' },
  { a: 'PMTUD', d: 'Path MTU Discovery — descubrimiento automático de la MTU mínima de la ruta', cat: 'redes' },
  { a: 'RADIUS', d: 'protocolo AAA (Authentication, Authorization, Accounting) para acceso a red', cat: 'redes' },
  { a: 'SD-WAN', d: 'Software-Defined WAN — gestión centralizada de enlaces WAN con políticas por aplicación', cat: 'redes' },
  { a: 'SNMP', d: 'Simple Network Management Protocol — monitorización (v1/2c en claro: usar v3 con auth)', cat: 'redes' },
  { a: 'STP', d: 'Spanning Tree Protocol — previene bucles de capa 2 (sus ataques: root bridge hijack)', cat: 'redes' },
  { a: 'TTL', d: 'Time To Live — saltos máximos de un paquete; su valor residual delata el SO y la distancia', cat: 'redes' },
  { a: 'VLAN', d: 'Virtual LAN — segmentación lógica de capa 2 (1-4094; la 1 es la insegura default)', cat: 'redes' },
  { a: 'VPN', d: 'Virtual Private Network — túnel cifrado entre redes o hosts (IPsec, WireGuard, OpenVPN)', cat: 'redes' },
  { a: 'VXLAN', d: 'Virtual eXtensible LAN — VLANs sobre UDP para datacenters (16M de segmentos)', cat: 'redes' },
  { a: 'WPA2/WPA3', d: 'WiFi Protected Access — cifrado WiFi; WPA2-Enterprise usa 802.1X; WPA3 soluciona el crackeo offline (SAE)', cat: 'redes' },
  { a: '802.1X', d: 'autenticación de puerto de red (supplicant-authenticator-server RADIUS): NAC por excelencia', cat: 'redes' },

  // cripto
  { a: 'AES', d: 'Advanced Encryption Standard — cifrado simétrico por bloques (128/192/256 bits); usa siempre GCM o CBC con HMAC', cat: 'cripto' },
  { a: 'AEAD', d: 'Authenticated Encryption with Associated Data — cifrado que también autentica (GCM, ChaCha20-Poly1305)', cat: 'cripto' },
  { a: 'CA', d: 'Certificate Authority — entidad que firma certificados (raíz de confianza de TLS)', cat: 'cripto' },
  { a: 'CBC', d: 'Cipher Block Chaining — modo de AES vulnerable a padding oracle sin MAC', cat: 'cripto' },
  { a: 'CTR', d: 'Counter Mode — AES como stream cipher; NUNCA reutilizar nonce', cat: 'cripto' },
  { a: 'GCM', d: 'Galois/Counter Mode — AEAD moderno: cifrado + autenticación en un paso', cat: 'cripto' },
  { a: 'HMAC', d: 'Hash-based MAC — autenticación de mensajes con clave (HMAC-SHA256)', cat: 'cripto' },
  { a: 'JWT', d: 'JSON Web Token — token firmado (HS256/RS256); el alg=none es el fallo clásico', cat: 'cripto' },
  { a: 'PBKDF2', d: 'Password-Based Key Derivation Function — derivación de claves desde contraseñas', cat: 'cripto' },
  { a: 'PGP/GPG', d: 'Pretty Good Privacy — cifrado de correo y ficheros con clave pública/privada', cat: 'cripto' },
  { a: 'PKI', d: 'Public Key Infrastructure — sistema completo de certificados (CA, CRL, OCSP)', cat: 'cripto' },
  { a: 'RSA', d: 'cifrado asimétrico de Rivest-Shamir-Adleman (claves 2048+ bits hoy)', cat: 'cripto' },
  { a: 'SHA', d: 'Secure Hash Algorithm — familia de hashes (SHA-256 actual; MD5/SHA-1 rotos)', cat: 'cripto' },
  { a: 'TLS', d: 'Transport Layer Security — cifrado de transporte (sucesor de SSL); 1.2 mínimo, 1.3 preferido', cat: 'cripto' },
  { a: 'TOTP / HOTP', d: 'Time/HTTP-based One-Time Password — códigos 2FA de 6 dígitos (Google Authenticator)', cat: 'cripto' },
  { a: 'OTP', d: 'One-Time Password — código de un solo uso (SMS, app, hardware token)', cat: 'cripto' },
  { a: 'X.509', d: 'formato estándar de certificados digitales (pem/der/crt)', cat: 'cripto' },

  // windows / AD
  { a: 'AD', d: 'Active Directory — directorio de Microsoft: usuarios, equipos, dominios, GPOs', cat: 'win-ad' },
  { a: 'ACL (AD)', d: 'Access Control List — permisos de objetos AD; los ACE peligrosos habilitan ataques de delegación', cat: 'win-ad' },
  { a: 'AS-REP', d: 'primera respuesta del KDC en Kerberos; usuarios sin preauth permiten AS-REP Roasting', cat: 'win-ad' },
  { a: 'DC', d: 'Domain Controller — servidor que autentica en AD (con la BD NTDS.dit)', cat: 'win-ad' },
  { a: 'DACL / SACL', d: 'Discretionary/System ACL — quién puede qué sobre un objeto / qué auditar', cat: 'win-ad' },
  { a: 'DPAPI', d: 'Data Protection API — cifrado de credenciales de usuario en Windows (Chrome, credenciales…)', cat: 'win-ad' },
  { a: 'GPO', d: 'Group Policy Object — configuración centralizada aplicada a OUs de AD', cat: 'win-ad' },
  { a: 'KDC / KRB', d: 'Key Distribution Center — servicio Kerberos del DC que emite TGT/TGS', cat: 'win-ad' },
  { a: 'Kerberoasting', d: 'pedir TGS de cuentas con SPN y crackear su NTLM offline', cat: 'win-ad' },
  { a: 'LSASS', d: 'Local Security Authority Subsystem — proceso que guarda credenciales en memoria (objetivo de mimikatz)', cat: 'win-ad' },
  { a: 'LLMNR', d: 'Link-Local Multicast Name Resolution — resolutivo local de Windows, abusable con Responder', cat: 'win-ad' },
  { a: 'NTLM', d: 'protocolo de autenticación legacy de Windows (hash NT: su cracking es rápido)', cat: 'win-ad' },
  { a: 'NTDS.dit', d: 'base de datos del AD en el DC: contiene TODOS los hashes (extraída con secretsdump)', cat: 'win-ad' },
  { a: 'PPL', d: 'Protected Process Light — protección de LSASS contra lectura de memoria', cat: 'win-ad' },
  { a: 'SAM', d: 'Security Account Manager — BD de usuarios locales de Windows (hashes LM/NT)', cat: 'win-ad' },
  { a: 'SID / RID', d: 'Security Identifier / Relative ID — identificador de objeto en Windows (RID 500 = admin local)', cat: 'win-ad' },
  { a: 'SPN', d: 'Service Principal Name — identificador de servicio para Kerberos', cat: 'win-ad' },
  { a: 'TGT / TGS', d: 'Ticket Granting Ticket / Service Ticket — tickets de Kerberos (Golden/Silver ticket los forjan)', cat: 'win-ad' },
  { a: 'UAC', d: 'User Account Control — consentimiento de elevación en Windows (y su abuso: UAC bypass)', cat: 'win-ad' },
  { a: 'WinRM', d: 'Windows Remote Management — shell remota de Windows (5985/5986), el SSH de Windows', cat: 'win-ad' },

  // linux
  { a: 'ACL (Linux)', d: 'Access Control Lists POSIX — permisos finos además de los rwx clásicos (getfacl/setfacl)', cat: 'linux' },
  { a: 'Capabilities', d: 'privilegios granulares de Linux (cap_net_raw, cap_setuid…) — getcap -r / las delata', cat: 'linux' },
  { a: 'cron / crontab', d: 'planificador de tareas por tiempo; los crons escribibles son persistencia y privesc', cat: 'linux' },
  { a: 'init / systemd', d: 'PID 1 y gestor de servicios moderno (units, timers, journal)', cat: 'linux' },
  { a: 'LUKS', d: 'Linux Unified Key Setup — cifrado de disco estándar de Linux (cryptsetup)', cat: 'linux' },
  { a: 'LVM', d: 'Logical Volume Manager — capa de abstracción de discos (PV→VG→LV) para redimensionar en caliente', cat: 'linux' },
  { a: 'nftables', d: 'firewall moderno del kernel Linux (sucesor de iptables)', cat: 'linux' },
  { a: 'PAM', d: 'Pluggable Authentication Modules — autenticación modular de Linux (pam_pwquality, pam_google_auth…)', cat: 'linux' },
  { a: 'RAID', d: 'Redundant Array of Inexpensive Disks — combinación de discos (0/1/5/10) por HW o mdadm', cat: 'linux' },
  { a: 'SUID / SGID', d: 'Set User/Group ID — bit que ejecuta un binario con los permisos de su dueño; base del privesc', cat: 'linux' },
  { a: 'SELinux / AppArmor', d: 'módulos de seguridad MAC obligatoria (RedHat/Ubuntu) que confinan procesos', cat: 'linux' },
  { a: 'sudo / sudoers', d: 'elevación controlada de privilegios; sudoers.d con GTFOBins auditados', cat: 'linux' },
  { a: 'swap', d: 'área de intercambio en disco cuando la RAM se llena (y soporte de hibernación)', cat: 'linux' },
  { a: 'sysctl', d: 'interfaz de parámetros del kernel (/proc/sys) — hardening de red y kernel', cat: 'linux' },
  { a: 'systemd timer', d: 'alternativa moderna a cron con journal, dependencias y persistencia', cat: 'linux' },

  // web
  { a: 'API', d: 'Application Programming Interface — interfaz de programación (REST, GraphQL, gRPC)', cat: 'web' },
  { a: 'CDN', d: 'Content Delivery Network — caché geográfica de contenido (Cloudflare, Akamai)', cat: 'web' },
  { a: 'CORS', d: 'Cross-Origin Resource Sharing — control de qué orígenes puede llamar una web', cat: 'web' },
  { a: 'CORS misconfig', d: 'Access-Control-Allow-Origin: * con credenciales, o reflejo del Origin: roba datos cross-site', cat: 'web' },
  { a: 'CSP', d: 'Content Security Policy — cabecera que restringe qué scripts puede cargar una página (anti-XSS)', cat: 'web' },
  { a: 'CSRF', d: 'Cross-Site Request Forgery — hacer que el navegador de la víctima envíe peticiones autenticadas', cat: 'web' },
  { a: 'DOM', d: 'Document Object Model — árbol de objetos del HTML; el XSS de tipo DOM no pasa por el servidor', cat: 'web' },
  { a: 'HTTP', d: 'HyperText Transfer Protocol — protocolo de la web (métodos, cabeceras, códigos de estado)', cat: 'web' },
  { a: 'IDOR', d: 'Insecure Direct Object Reference — acceso a objetos por ID sin validar permisos (/invoice/1042)', cat: 'web' },
  { a: 'JWT (web)', d: 'token de sesión sin estado; peligros: alg=none, keys confusas, subdominios con firma', cat: 'web' },
  { a: 'REST', d: 'Representational State Transfer — estilo de API con verbos HTTP y recursos', cat: 'web' },
  { a: 'SSO (web)', d: 'Single Sign-On — autenticación centralizada; sus fallos: redirect_uri laxo, firma ignorada', cat: 'web' },
  { a: 'SQLi blind', d: 'SQL injection sin reflejo de datos: inferencia por booleanos o por tiempo (sleep)', cat: 'web' },
  { a: 'SSTI', d: 'Server-Side Template Injection — inyección en plantillas del servidor (Jinja2, Twig): RCE directo', cat: 'web' },
  { a: 'WAF bypass', d: 'técnicas de evasión: encoding, case, comentarios SQL, headers raros, HTTP/2 smuggling', cat: 'web' },

  // cloud
  { a: 'AWS / GCP / Azure', d: 'las tres hyperscaladoras: cada una con su modelo IAM, logging y servicios', cat: 'cloud' },
  { a: 'AZ', d: 'Availability Zone — datacenter independiente dentro de una región cloud', cat: 'cloud' },
  { a: 'CSPM', d: 'Cloud Security Posture Management — auditoría continua de configs cloud (buckets abiertos…)', cat: 'cloud' },
  { a: 'IAM (cloud)', d: 'Identity and Access Management del proveedor: políticas, roles, federation', cat: 'cloud' },
  { a: 'IaaS / PaaS / SaaS', d: 'Infra/Platform/Software as a Service — quién gestiona qué en cada modelo', cat: 'cloud' },
  { a: 'S3 bucket', d: 'almacenamiento de AWS; los públicos por error son la fuga clásica', cat: 'cloud' },
  { a: 'serverless', d: 'funciones sin servidor (Lambda, Cloud Functions) — superficie nueva: event injection', cat: 'cloud' },
  { a: 'metadata SSRF', d: 'SSRF a 169.254.169.254 roba credenciales IAM temporales en todas las clouds', cat: 'cloud' },
  { a: 'tenant', d: 'inquilino: aislamiento lógico entre clientes en multi-tenancy', cat: 'cloud' },

  // gobierno / marco
  { a: 'ISO 27001', d: 'estándar internacional de SGSI (Sistema de Gestión de Seguridad de la Información)', cat: 'gobierno' },
  { a: 'NIST', d: 'National Institute of Standards and Technology — frameworks (CSF, 800-53, 800-63B de passwords)', cat: 'gobierno' },
  { a: 'MITRE ATT&CK', d: 'matriz de tácticas y técnicas de adversarios reales (Initial Access → Impact)', cat: 'gobierno' },
  { a: 'OWASP', d: 'Open Worldwide Application Security Project — Top 10 de riesgos web y guías (ASVS)', cat: 'gobierno' },
  { a: 'GDPR / RGPD', d: 'General Data Protection Regulation — regulación europea de datos personales', cat: 'gobierno' },
  { a: 'ENS', d: 'Esquema Nacional de Seguridad — marco español de seguridad para administraciones y proveedores', cat: 'gobierno' },
  { a: 'PCI DSS', d: 'Payment Card Industry Data Security Standard — requisitos para quien trata tarjetas', cat: 'gobierno' },
  { a: 'risk assessment', d: 'identificación y valoración de riesgos (probabilidad × impacto)', cat: 'gobierno' },
  { a: 'threat model', d: 'modelado de amenazas: qué puede ir mal, a quién le importa y qué hacemos (STRIDE, PASTA)', cat: 'gobierno' },
  { a: 'BIA', d: 'Business Impact Analysis — cuánto cuesta que un servicio caiga (base del BC/DR)', cat: 'gobierno' },
  { a: 'BCP / DRP', d: 'Business Continuity / Disaster Recovery Plan — continuidad y recuperación ante desastres', cat: 'gobierno' },
  { a: 'pentest', d: 'prueba de penetración con alcance y autorización definidos, que termina en informe', cat: 'gobierno' },
  { a: 'bug bounty', d: 'programa de recompensas por vulnerabilidades encontradas dentro de un scope', cat: 'gobierno' },
  { a: 'BAS', d: 'Breach and Attack Simulation — validación continua de controles ejecutando ataques simulados', cat: 'gobierno' },
  { a: 'RTO / RPO', d: 'Recovery Time / Recovery Point Objective — cuánto tardas en restaurar y cuántos datos puedes perder', cat: 'gobierno' },

  // forense / malware
  { a: 'DFIR', d: 'Digital Forensics and Incident Response — forense digital y respuesta a incidentes', cat: 'forense' },
  { a: 'chain of custody', d: 'cadena de custodia — registro inviolable de quién maneja la evidencia y cuándo', cat: 'forense' },
  { a: 'disk image', d: 'copia bit a bit de un disco (dd, FTK Imager) con hash verificado', cat: 'forense' },
  { a: 'EVTX', d: 'formato de logs de Windows (Security, System, Sysmon/Operational)', cat: 'forense' },
  { a: 'IOC (forense)', d: 'ver IOC en defensivo: hashes, IPs, dominios, mutex, registry keys', cat: 'forense' },
  { a: 'lateral movement', d: 'movimiento lateral — pasar de una máquina comprometida a otras (SMB, WinRM, RDP)', cat: 'forense' },
  { a: 'malware analysis', d: 'análisis de malware: estático (strings, imports) y dinámico (sandbox, debug)', cat: 'forense' },
  { a: 'packer', d: 'compresor/cifrador de binarios para evadir firmas (UPX, crypters custom)', cat: 'forense' },
  { a: 'persistence', d: 'persistencia — mecanismos para sobrevivir a reinicios (Run keys, servicios, crons, WMI)', cat: 'forense' },
  { a: 'sandbox', d: 'entorno aislado de ejecución para observar malware sin riesgo (Cuckoo, Any.Run)', cat: 'forense' },
  { a: 'steganography', d: 'ocultar datos dentro de otros (LSB en imágenes, metadatos)', cat: 'forense' },
  { a: 'timeline', d: 'línea temporal de artefactos (ficheros, logs, registro) reconstruida del incidente', cat: 'forense' },
  { a: 'timestomping', d: 'manipular timestamps de ficheros para confundir al forense (Sysmon E2 lo delata)', cat: 'forense' },
  { a: 'YARA', d: 'lenguaje de reglas para identificar familias de malware por patrones', cat: 'forense' },
  { a: 'Volatile', d: 'artefactos volátiles: memoria RAM, procesos, conexiones — se pierden al apagar (orden de adquisición)', cat: 'forense' },
  { a: 'SLA', d: 'Service Level Agreement — acuerdo de niveles de servicio (también para el SOC: tiempo de respuesta)', cat: 'gobierno' },
]

export function searchAcronyms(q: string, cat: AcroCat | 'todas'): Acronym[] {
  const qn = q.trim().toLowerCase()
  return ACRONYMS.filter((x) => {
    if (cat !== 'todas' && x.cat !== cat) return false
    if (!qn) return true
    return x.a.toLowerCase().includes(qn) || x.d.toLowerCase().includes(qn)
  })
}
